import { Category } from "@/generated/prisma/client";

export const MARKUP = 10;

export function getMarkup(category: Category): number {
  // Энергетики, напитки и чай/кофе — наценка +20₽ вместо стандартных +10₽.
  const MARKUP_20_CATEGORIES: Category[] = [Category.ENERGY, Category.OTHER, Category.COFFEE_TEA];
  return MARKUP_20_CATEGORIES.includes(category) ? 20 : MARKUP;
}

export function computeSellPrice(purchasePrice: number, markup: number): number {
  return purchasePrice + markup;
}

export type SeedProduct = {
  name: string;
  category: Category;
  volumeMl: number | null;
  weightGrams?: number;
  purchasePrice: number;
  caseSize: number;
  imageUrl?: string;
  /** Наценка для конкретного товара, если она отличается от стандартной
   * для его категории (см. getMarkup) — например, когда поставщик даёт
   * разную закупочную цену на похожие товары одной категории. */
  markup?: number;
  /** Короткое описание для карточки товара (без пищевой ценности — она в отдельных полях). */
  description?: string;
  /** Пищевая ценность на 100 г/мл — калории. */
  calories?: number;
  /** Пищевая ценность на 100 г/мл — белки, г. */
  protein?: number;
  /** Пищевая ценность на 100 г/мл — жиры, г. */
  fat?: number;
  /** Пищевая ценность на 100 г/мл — углеводы, г. */
  carbs?: number;
};

// Наименования, закупочные цены и размер упаковки — из прайс-листа поставщика (2026-07-03).
// Товар продаётся только целой упаковкой (caseSize шт.), розничной продажи по 1 шт. нет.
// Одинаковые позиции, встречавшиеся в прайсе дважды, объединены в одну строку.
export const seedProducts: SeedProduct[] = [
  // Пиво
  { name: "Балтика №0 белое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 60, caseSize: 24, imageUrl: "/baltika-0-beloe-jb.jpg", description: "Безалкогольное пшеничное пиво, лёгкое и освежающее.", calories: 25, protein: 0.3, fat: 0, carbs: 5.8 },
  { name: "Балтика №0 пшеничное (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 59, caseSize: 24, imageUrl: "/baltika-0-pshenichnoe-jb.jpg", description: "Безалкогольное пшеничное пиво с мягким солодовым вкусом.", calories: 24, protein: 0.3, fat: 0, carbs: 5.5 },
  { name: "Балтика №3 (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 72, caseSize: 24, imageUrl: "/baltika-3-jb.jpg", description: "Классическое светлое пиво.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Балтика №7 мягкое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 72, caseSize: 24, imageUrl: "/baltika-7-myagkoe-jb.jpg", description: "Мягкое экспортное пиво со сбалансированным вкусом.", calories: 47, protein: 0.4, fat: 0, carbs: 3.6 },
  { name: "Балтика №7 (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 83, caseSize: 20, imageUrl: "/baltika-7-stb.jpg", description: "Мягкое экспортное пиво со сбалансированным вкусом.", calories: 47, protein: 0.4, fat: 0, carbs: 3.6 },
  { name: "Балтика №7 (ПЭТ)", category: Category.BEER, volumeMl: null, purchasePrice: 110, caseSize: 9, imageUrl: "/baltika-7-pet.jpg", description: "Мягкое экспортное пиво со сбалансированным вкусом.", calories: 47, protein: 0.4, fat: 0, carbs: 3.6 },
  { name: "Балтика №9 (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 67, caseSize: 24, imageUrl: "/baltika-9-jb.jpg", description: "Крепкое пиво с насыщенным солодовым вкусом.", calories: 62, protein: 0.4, fat: 0, carbs: 3.8 },
  { name: "Балтика №9 (ПЭТ)", category: Category.BEER, volumeMl: 1300, purchasePrice: 127, caseSize: 9, imageUrl: "/baltika-9-pet.jpg", description: "Крепкое пиво с насыщенным солодовым вкусом.", calories: 62, protein: 0.4, fat: 0, carbs: 3.8 },
  { name: "Балтика Кулер (ПЭТ)", category: Category.BEER, volumeMl: 1250, purchasePrice: 128, caseSize: 9, imageUrl: "/baltika-kuler-pet.jpg", description: "Освежающий слабоалкогольный коктейль с фруктовым вкусом.", calories: 48, protein: 0.2, fat: 0, carbs: 6 },
  { name: "Крон Бланш Бьер (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 91, caseSize: 24, imageUrl: "/krone-blanche-jb.jpg", description: "Бельгийское пшеничное пиво с нотами апельсина и кориандра.", calories: 44, protein: 0.4, fat: 0, carbs: 3.7 },
  { name: "Крон Бланш Бьер (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 91, caseSize: 20, imageUrl: "/krone-blanche-stb.jpg", description: "Бельгийское пшеничное пиво с нотами апельсина и кориандра.", calories: 44, protein: 0.4, fat: 0, carbs: 3.7 },
  { name: "Гаррет Черная вишня (ст/б)", category: Category.BEER, volumeMl: 400, purchasePrice: 81, caseSize: 20, imageUrl: "/garret-chernaya-vishnya-stb.jpg", description: "Пивной напиток с ярким вкусом чёрной вишни.", calories: 49, protein: 0.2, fat: 0, carbs: 6.2 },
  { name: "Жатецкий Гусь (ПЭТ)", category: Category.BEER, volumeMl: 1350, purchasePrice: 147, caseSize: 9, imageUrl: "/zateckiy-gus-pet.jpg", description: "Светлое пиво чешского стиля с мягкой горчинкой.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Жатецкий Гусь (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 83, caseSize: 24, imageUrl: "/zateckiy-gus-jb.jpg", description: "Светлое пиво чешского стиля с мягкой горчинкой.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Дон (ПЭТ)", category: Category.BEER, volumeMl: 1500, purchasePrice: 123, caseSize: 9, imageUrl: "/don-pet.jpg", description: "Светлое пиво с классическим солодовым вкусом.", calories: 44, protein: 0.4, fat: 0, carbs: 3.4 },
  { name: "Кулер (ст/б)", category: Category.BEER, volumeMl: 470, purchasePrice: 68, caseSize: 20, imageUrl: "/kuler-stb.jpg", description: "Освежающий слабоалкогольный коктейль с фруктовым вкусом.", calories: 48, protein: 0.2, fat: 0, carbs: 6 },
  { name: "Кулер (ж/б)", category: Category.BEER, volumeMl: 470, purchasePrice: 70, caseSize: 24, imageUrl: "/kuler-jb.jpg", description: "Освежающий слабоалкогольный коктейль с фруктовым вкусом.", calories: 48, protein: 0.2, fat: 0, carbs: 6 },
  { name: "Охота крепкое (ПЭТ)", category: Category.BEER, volumeMl: 1250, purchasePrice: 130, caseSize: 9, imageUrl: "/ohota-krepkoe-pet.jpg", description: "Крепкое пиво с выраженным солодовым вкусом.", calories: 63, protein: 0.4, fat: 0, carbs: 3.9 },
  { name: "Голд Майн Бир (ПЭТ)", category: Category.BEER, volumeMl: 1200, purchasePrice: 112, caseSize: 9, imageUrl: "/gold-mine-beer-pet.jpg", description: "Светлое пиво с лёгкой хмелевой горчинкой.", calories: 44, protein: 0.4, fat: 0, carbs: 3.4 },
  { name: "Бочкарев Холод и Солод светлое (ПЭТ)", category: Category.BEER, volumeMl: 950, purchasePrice: 105, caseSize: 9, imageUrl: "/bochkarev-holod-i-solod-pet.jpg", description: "Светлое пиво с чистым солодовым вкусом.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Бочкарев Живой Розлив светлое (ПЭТ)", category: Category.BEER, volumeMl: 950, purchasePrice: 105, caseSize: 9, imageUrl: "/bochkarev-zhivoi-rozliv-pet.jpg", description: "Непастеризованное светлое пиво живого розлива.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Белый Медведь Светлое (ПЭТ)", category: Category.BEER, volumeMl: 1200, purchasePrice: 115, caseSize: 9, imageUrl: "/belyi-medved-svetloe-pet.jpg", description: "Светлое пиво с мягким вкусом.", calories: 44, protein: 0.4, fat: 0, carbs: 3.4 },
  { name: "Белый Медведь Крепкое (ПЭТ)", category: Category.BEER, volumeMl: 1150, purchasePrice: 135, caseSize: 9, imageUrl: "/belyi-medved-krepkoe-pet.jpg", description: "Крепкое пиво с насыщенным вкусом.", calories: 64, protein: 0.4, fat: 0, carbs: 4 },
  { name: "Эфес Пилсенер (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 82, caseSize: 20, imageUrl: "/efes-pilsener-stb.jpg", description: "Турецкий светлый пилснер с хмелевой горчинкой.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Эсса Солнце на пляже (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 79, caseSize: 24, imageUrl: "/essa-sun-on-beach-stb.jpg", description: "Пивной напиток с ярким тропическим фруктовым вкусом.", calories: 50, protein: 0.2, fat: 0, carbs: 6.5 },
  { name: "Шпатен Мюнхен Хеллес (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 116, caseSize: 20, imageUrl: "/spaten-munchen-stb.jpg", description: "Баварское светлое пиво мюнхенского стиля.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Хугарден Грейпфрут (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 90, caseSize: 20, imageUrl: "/hoegaarden-grapefruit-stb.jpg", description: "Бельгийское пшеничное пиво с грейпфрутовым акцентом.", calories: 46, protein: 0.4, fat: 0, carbs: 4.8 },
  { name: "Хугарден Вишня (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 90, caseSize: 20, imageUrl: "/hoegaarden-vishnya-stb.jpg", description: "Бельгийское пшеничное пиво с вишнёвым акцентом.", calories: 46, protein: 0.4, fat: 0, carbs: 4.8 },
  { name: "Хугарден (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 90, caseSize: 20, imageUrl: "/hoegaarden-stb.jpg", description: "Классическое бельгийское пшеничное пиво с кориандром и апельсиновой цедрой.", calories: 44, protein: 0.4, fat: 0, carbs: 3.7 },
  { name: "Стелла (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 102, caseSize: 20, imageUrl: "/stella-stb.jpg", description: "Бельгийский светлый лагер премиум-класса.", calories: 45, protein: 0.4, fat: 0, carbs: 3.4 },
  { name: "Старый Мельник из Бочонка мягкое (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 74, caseSize: 12, imageUrl: "/stariy-melnik-bochonka-stb.jpg", description: "Мягкое светлое пиво с бархатистым вкусом.", calories: 43, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Редд's (ст/б)", category: Category.BEER, volumeMl: 330, purchasePrice: 82, caseSize: 24, imageUrl: "/redds-stb.jpg", description: "Пивной напиток с яблочным вкусом.", calories: 47, protein: 0.2, fat: 0, carbs: 6 },
  { name: "Мягкий Солод Светлое 4.2% (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 58, caseSize: 12, imageUrl: "/myagkiy-solod-42-stb.jpg", description: "Лёгкое светлое пиво с мягким вкусом.", calories: 41, protein: 0.4, fat: 0, carbs: 3.2 },
  { name: "Миллер (ст/б)", category: Category.BEER, volumeMl: 500, purchasePrice: 72, caseSize: 20, imageUrl: "/miller-stb.jpg", description: "Американский светлый лагер с лёгким хмелевым вкусом.", calories: 43, protein: 0.3, fat: 0, carbs: 3.2 },
  { name: "Корона Экстра (ст/б)", category: Category.BEER, volumeMl: 355, purchasePrice: 118, caseSize: 24, imageUrl: "/corona-extra-stb.jpg", description: "Мексиканское светлое пиво с освежающим вкусом.", calories: 42, protein: 0.3, fat: 0, carbs: 3.1 },
  { name: "Козел Тёмное (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 20, imageUrl: "/kozel-temnoe-stb.jpg", description: "Тёмное чешское пиво с карамельными нотами.", calories: 48, protein: 0.4, fat: 0, carbs: 4 },
  { name: "Козел Светлое (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 20, imageUrl: "/kozel-svetloe-stb.jpg", description: "Светлое чешское пиво с мягкой горчинкой.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Жигули Барное (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 68, caseSize: 20, imageUrl: "/zhiguli-barnoe-stb.jpg", description: "Светлое пиво по классической рецептуре.", calories: 42, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Жигули 1968 (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 64, caseSize: 20, imageUrl: "/zhiguli-1968-stb.jpg", description: "Светлое пиво по рецепту образца 1968 года.", calories: 42, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Доктор Дизель Малина-Лайм (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 77, caseSize: 20, imageUrl: "/dr-diesel-malina-laym-stb.jpg", description: "Пивной напиток со вкусом малины и лайма.", calories: 49, protein: 0.2, fat: 0, carbs: 6.3 },
  { name: "Гринбит (ст/б)", category: Category.BEER, volumeMl: 480, purchasePrice: 75, caseSize: 20, imageUrl: "/grinbit-stb.jpg", description: "Светлое пиво с лёгким освежающим вкусом.", calories: 43, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Гаррет Грейпфрут (ст/б)", category: Category.BEER, volumeMl: 400, purchasePrice: 87, caseSize: 20, imageUrl: "/garret-greypfrut-stb.jpg", description: "Пивной напиток с грейпфрутовым вкусом.", calories: 49, protein: 0.2, fat: 0, carbs: 6.2 },
  { name: "Брамма (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 70, caseSize: 20, imageUrl: "/bramma-stb.jpg", description: "Светлое пиво со сбалансированным вкусом.", calories: 43, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Бочкарев Холод и Солод светлое (ст/б)", category: Category.BEER, volumeMl: 430, purchasePrice: 69, caseSize: 20, imageUrl: "/bochkarev-holod-i-solod-stb.jpg", description: "Светлое пиво с чистым солодовым вкусом.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Бад (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 100, caseSize: 20, imageUrl: "/bad-stb.jpg", description: "Американский светлый лагер с лёгким вкусом.", calories: 43, protein: 0.3, fat: 0, carbs: 3.2 },
  { name: "Амстердам (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 92, caseSize: 20, description: "Светлое пиво голландского стиля.", calories: 44, protein: 0.4, fat: 0, carbs: 3.4 },
  { name: "Эфес Пилсенер (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 80, caseSize: 24, imageUrl: "/efes-pilsener-jb.jpg", description: "Турецкий светлый пилснер с хмелевой горчинкой.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Шпатен (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 118, caseSize: 24, imageUrl: "/spaten-jb.jpg", description: "Баварское светлое пиво мюнхенского стиля.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Мягкий Солод Светлое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 58, caseSize: 12, imageUrl: "/myagkiy-solod-jb.jpg", description: "Лёгкое светлое пиво с мягким вкусом.", calories: 41, protein: 0.4, fat: 0, carbs: 3.2 },
  { name: "Охота крепкое (ж/б)", category: Category.BEER, volumeMl: 430, purchasePrice: 63, caseSize: 24, imageUrl: "/ohota-krepkoe-jb.jpg", description: "Крепкое пиво с выраженным солодовым вкусом.", calories: 63, protein: 0.4, fat: 0, carbs: 3.9 },
  { name: "Жигули Барное (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 68, caseSize: 24, imageUrl: "/zhiguli-barnoe-jb.jpg", description: "Светлое пиво по классической рецептуре.", calories: 42, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Гринбит (ж/б)", category: Category.BEER, volumeMl: 480, purchasePrice: 75, caseSize: 24, imageUrl: "/grinbit-jb.jpg", description: "Светлое пиво с лёгким освежающим вкусом.", calories: 43, protein: 0.4, fat: 0, carbs: 3.3 },
  { name: "Велкопоповицкий Козел Тёмное (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 24, imageUrl: "/kozel-temnoe-jb.jpg", description: "Тёмное чешское пиво с карамельными нотами.", calories: 48, protein: 0.4, fat: 0, carbs: 4 },
  { name: "Велкопоповицкий Козел Светлое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 24, imageUrl: "/kozel-svetloe-jb.jpg", description: "Светлое чешское пиво с мягкой горчинкой.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Бад (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 100, caseSize: 24, imageUrl: "/bad-jb.jpg", description: "Американский светлый лагер с лёгким вкусом.", calories: 43, protein: 0.3, fat: 0, carbs: 3.2 },
  { name: "Ловенбрау (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 82, caseSize: 24, imageUrl: "/lowenbrau-jb.jpg", description: "Баварское светлое пиво с мягким вкусом.", calories: 45, protein: 0.4, fat: 0, carbs: 3.5 },
  { name: "Эсса Ананас Грейпфрут (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 79, caseSize: 20, markup: 10, imageUrl: "/essa-ananas-greypfrut.jpg", description: "Пивной напиток со вкусом ананаса и грейпфрута.", calories: 50, protein: 0.2, fat: 0, carbs: 6.5 },

  // Энергетики
  { name: "Adrenaline Rush Sugar Free (White)", category: Category.ENERGY, volumeMl: 449, purchasePrice: 98, caseSize: 12, imageUrl: "/adrenaline-rush-zero-white.jpg", description: "Энергетик без сахара с кофеином и таурином (~30 мг кофеина/100 мл).", calories: 3, protein: 0, fat: 0, carbs: 0.5 },
  { name: "Adrenaline Rush", category: Category.ENERGY, volumeMl: 250, purchasePrice: 75, caseSize: 12, imageUrl: "/adrenaline-rush-025-jb.jpg", description: "Классический энергетик с кофеином и таурином (~30 мг кофеина/100 мл).", calories: 48, protein: 0, fat: 0, carbs: 11 },
  { name: "Adrenaline Rush", category: Category.ENERGY, volumeMl: 449, purchasePrice: 102, caseSize: 12, imageUrl: "/adrenaline-rush-classic.jpg", description: "Классический энергетик с кофеином и таурином (~30 мг кофеина/100 мл).", calories: 48, protein: 0, fat: 0, carbs: 11 },
  { name: "Flash Berry", category: Category.ENERGY, volumeMl: 440, purchasePrice: 63, caseSize: 24, imageUrl: "/flash-yagodniy-jb.jpg", description: "Энергетик с ягодным вкусом и кофеином (~30 мг/100 мл).", calories: 46, protein: 0, fat: 0, carbs: 11 },
  { name: "Flash", category: Category.ENERGY, volumeMl: 1000, purchasePrice: 88, caseSize: 9, imageUrl: "/flash-pet-1l.jpg", description: "Классический энергетический напиток с кофеином (~30 мг/100 мл).", calories: 46, protein: 0, fat: 0, carbs: 11 },
  { name: "Flash", category: Category.ENERGY, volumeMl: 500, purchasePrice: 63, caseSize: 20, imageUrl: "/flash-pet-05.jpg", description: "Классический энергетический напиток с кофеином (~30 мг/100 мл).", calories: 46, protein: 0, fat: 0, carbs: 11 },
  { name: "Black Monster Ultra Fantasy", category: Category.ENERGY, volumeMl: 500, purchasePrice: 165, caseSize: 12, imageUrl: "/monster-ultra-black.jpg", description: "Низкокалорийный энергетик с лёгким фруктовым вкусом и кофеином (~32 мг/100 мл).", calories: 10, protein: 0.3, fat: 0, carbs: 2 },
  { name: "Tornado Storm", category: Category.ENERGY, volumeMl: 450, purchasePrice: 66, caseSize: 12, imageUrl: "/tornado-storm.jpg", description: "Энергетик с ярким фруктовым вкусом и кофеином (~30 мг/100 мл).", calories: 47, protein: 0, fat: 0, carbs: 11.5 },
  { name: "Tornado Mango", category: Category.ENERGY, volumeMl: 1000, purchasePrice: 89, caseSize: 6, imageUrl: "/tornado-mango-pet.jpg", description: "Энергетик со вкусом манго и кофеином (~30 мг/100 мл).", calories: 47, protein: 0, fat: 0, carbs: 11.5 },
  { name: "Mountain Dew", category: Category.OTHER, volumeMl: 1000, purchasePrice: 95, caseSize: 9, imageUrl: "/mountain-dew-pet-1l.jpg", description: "Газированный цитрусовый напиток с кофеином.", calories: 46, protein: 0, fat: 0, carbs: 11.5 },
  { name: "Mountain Dew", category: Category.OTHER, volumeMl: 500, purchasePrice: 74, caseSize: 12, imageUrl: "/mountain-dew-pet-05.jpg", description: "Газированный цитрусовый напиток с кофеином.", calories: 46, protein: 0, fat: 0, carbs: 11.5 },
  { name: "Mountain Dew", category: Category.OTHER, volumeMl: 330, purchasePrice: 64, caseSize: 24, imageUrl: "/mountain-dew-jb.jpg", description: "Газированный цитрусовый напиток с кофеином.", calories: 46, protein: 0, fat: 0, carbs: 11.5 },
  { name: "Power Torr Mango", category: Category.ENERGY, volumeMl: 1000, purchasePrice: 90, caseSize: 6, imageUrl: "/power-torr-mango-pet.jpg", description: "Энергетик со вкусом манго и кофеином (~30 мг/100 мл).", calories: 46, protein: 0, fat: 0, carbs: 11 },
  { name: "Power Torr Blue", category: Category.ENERGY, volumeMl: 500, purchasePrice: 59, caseSize: 12, imageUrl: "/power-torr-siniy-pet.jpg", description: "Энергетик с ярким освежающим вкусом и кофеином (~30 мг/100 мл).", calories: 46, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Peach", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-peach.jpg", description: "Энергетик с персиковым вкусом и кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Raspberry Crush", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-malina-crush.jpg", description: "Энергетик с малиновым вкусом и кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Berry Coconut", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-berry-coconut.jpg", description: "Энергетик со вкусом ягод и кокоса, с кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Classic", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-classic.jpg", description: "Классический энергетический напиток с кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Original", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-original.jpg", description: "Классический энергетический напиток с кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Blueberry", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-blueberry.jpg", description: "Энергетик с черничным вкусом и кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Citrus Punch", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-citrus-punch.jpg", description: "Энергетик с цитрусовым вкусом и кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Lit Energy Strawberry Bubblegum", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-strawberry-bubblegum.jpg", description: "Энергетик со вкусом клубничной жвачки и кофеином (~30 мг/100 мл).", calories: 45, protein: 0, fat: 0, carbs: 11 },
  { name: "Volt Виноград-Гуава", category: Category.ENERGY, volumeMl: 450, purchasePrice: 74, caseSize: 24, imageUrl: "/volt-guava-jb.jpg", description: "Энергетик со вкусом винограда и гуавы, с кофеином (~30 мг/100 мл).", calories: 46, protein: 0, fat: 0, carbs: 11 },
  { name: "Gorilla Lychee & Pear", category: Category.ENERGY, volumeMl: 450, purchasePrice: 78, caseSize: 24, imageUrl: "/gorilla-lychee-pear-jb.jpg", description: "Энергетик со вкусом личи и груши, с кофеином (~30 мг/100 мл).", calories: 47, protein: 0, fat: 0, carbs: 11.5 },
  { name: "Flash Ultra", category: Category.ENERGY, volumeMl: 450, purchasePrice: 63, caseSize: 24, imageUrl: "/flesh-ultra-jb.jpg", description: "Низкокалорийный энергетик Ultra с кофеином (~30 мг/100 мл).", calories: 12, protein: 0.3, fat: 0, carbs: 2.5 },
  { name: "Burn Watermelon Sugar Free", category: Category.ENERGY, volumeMl: 500, purchasePrice: 88, caseSize: 12, imageUrl: "/burn-arbuz.jpg", description: "Энергетик без сахара со вкусом арбуза, с кофеином (~30 мг/100 мл).", calories: 3, protein: 0, fat: 0, carbs: 0.5 },
  { name: "Black Monster Ultra White", category: Category.ENERGY, volumeMl: 500, purchasePrice: 160, caseSize: 12, imageUrl: "/black-monster-ultra-white.jpg", description: "Низкокалорийный энергетик с лёгким освежающим вкусом и кофеином (~32 мг/100 мл).", calories: 10, protein: 0.3, fat: 0, carbs: 2 },

  // Напитки
  { name: "Добрый Pulpy Апельсин", category: Category.OTHER, volumeMl: 450, purchasePrice: 57, caseSize: 12, imageUrl: "/dobriy-pulpy-apelsin.jpg", description: "Сокосодержащий напиток с мякотью апельсина.", calories: 48, protein: 0.2, fat: 0, carbs: 11.5 },
  { name: "Мохито клубничный", category: Category.OTHER, volumeMl: 500, purchasePrice: 61, caseSize: 24, imageUrl: "/mohito-klubnichniy-jb.jpg", description: "Газированный напиток со вкусом клубничного мохито.", calories: 44, protein: 0, fat: 0, carbs: 10.5 },
  { name: "Добрый Апельсин/Фанта", category: Category.OTHER, volumeMl: 1000, purchasePrice: 75, caseSize: 12, imageUrl: "/dobriy-fanta-pet.jpg", description: "Газированный напиток с апельсиновым вкусом.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Добрый Фанта", category: Category.OTHER, volumeMl: 500, purchasePrice: 54, caseSize: 24, imageUrl: "/dobriy-fanta-pet.jpg", description: "Газированный напиток с апельсиновым вкусом.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Fanta", category: Category.OTHER, volumeMl: 330, purchasePrice: 55, caseSize: 12, imageUrl: "/fanta-jb.jpg", description: "Газированный напиток с апельсиновым вкусом.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Coca-Cola", category: Category.OTHER, volumeMl: 1000, purchasePrice: 59, caseSize: 9, imageUrl: "/koka-kola-1l.jpg", description: "Классический газированный напиток кола.", calories: 42, protein: 0, fat: 0, carbs: 10.6 },
  { name: "Coca-Cola", category: Category.OTHER, volumeMl: 2000, purchasePrice: 80, caseSize: 6, imageUrl: "/koka-kola-2l.jpg", description: "Классический газированный напиток кола.", calories: 42, protein: 0, fat: 0, carbs: 10.6 },
  { name: "Кола (Иран, ст/б)", category: Category.OTHER, volumeMl: 330, purchasePrice: 68, caseSize: 15, imageUrl: "/kola-iran-stb.jpg", description: "Газированный напиток со вкусом колы.", calories: 42, protein: 0, fat: 0, carbs: 10.5 },
  { name: "Pepsi", category: Category.OTHER, volumeMl: 2000, purchasePrice: 85, caseSize: 6, imageUrl: "/pepsi-2l.jpg", description: "Газированный напиток со вкусом колы.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Fanta", category: Category.OTHER, volumeMl: 2000, purchasePrice: 85, caseSize: 6, imageUrl: "/fanta-2l.jpg", description: "Газированный напиток с апельсиновым вкусом.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Pepsi", category: Category.OTHER, volumeMl: 1000, purchasePrice: 55, caseSize: 12, imageUrl: "/pepsi-1l.jpg", description: "Газированный напиток со вкусом колы.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Квас \"Вятский Хлебный\"", category: Category.OTHER, volumeMl: 1500, purchasePrice: 105, caseSize: 6, imageUrl: "/kvas-vyatskiy-hlebniy.jpg", description: "Традиционный хлебный квас натурального брожения.", calories: 27, protein: 0.2, fat: 0, carbs: 5.5 },
  { name: "Fanta", category: Category.OTHER, volumeMl: 1000, purchasePrice: 58, caseSize: 12, imageUrl: "/fanta-1l.jpg", description: "Газированный напиток с апельсиновым вкусом.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Sprite", category: Category.OTHER, volumeMl: 1000, purchasePrice: 58, caseSize: 12, imageUrl: "/sprite-1l.jpg", description: "Газированный напиток со вкусом лимона и лайма.", calories: 34, protein: 0, fat: 0, carbs: 8.5 },
  { name: "Вода \"Сестрица\" природная газ.", category: Category.OTHER, volumeMl: 1500, purchasePrice: 35, caseSize: 6, imageUrl: "/sestritsa-gaz-15l.jpg", description: "Природная питьевая вода с газом, без добавок.", calories: 0, protein: 0, fat: 0, carbs: 0 },
  { name: "Вода \"Сестрица\" природная негаз.", category: Category.OTHER, volumeMl: 1500, purchasePrice: 35, caseSize: 6, imageUrl: "/sestritsa-negaz-15l.jpg", description: "Природная питьевая вода без газа и добавок.", calories: 0, protein: 0, fat: 0, carbs: 0 },
  { name: "Вода \"Сестрица\" б/г", category: Category.OTHER, volumeMl: 500, purchasePrice: 25, caseSize: 12, imageUrl: "/sestritsa-bg-05l.jpg", description: "Природная питьевая вода без газа и добавок.", calories: 0, protein: 0, fat: 0, carbs: 0 },
  { name: "Сок \"Джу100\" Яблочно-грушевый", category: Category.OTHER, volumeMl: 1000, purchasePrice: 54, caseSize: 12, imageUrl: "/dju100-yabloko-grusha.jpg", description: "Сок прямого отжима из яблок и груш.", calories: 46, protein: 0.3, fat: 0, carbs: 11 },
  { name: "Напиток \"Ярмарка\" Лимонад", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-limonad.jpg", description: "Газированный лимонад с освежающим вкусом.", calories: 40, protein: 0, fat: 0, carbs: 10 },
  { name: "Напиток \"Ярмарка\" Тархун", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-tarhun.jpg", description: "Газированный напиток со вкусом эстрагона.", calories: 40, protein: 0, fat: 0, carbs: 10 },
  { name: "Напиток \"Ярмарка\" Мохито", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-mohito.jpg", description: "Газированный напиток со вкусом мохито.", calories: 40, protein: 0, fat: 0, carbs: 10 },
  { name: "Напиток \"Ярмарка\" Клубника", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-klubnika.jpg", description: "Газированный напиток с клубничным вкусом.", calories: 40, protein: 0, fat: 0, carbs: 10 },
  { name: "Напиток \"Натахтари\" Тархун (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-tarhun.jpg", description: "Грузинский газированный напиток со вкусом эстрагона.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Напиток \"Натахтари\" Груша (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-grusha.jpg", description: "Грузинский газированный напиток с грушевым вкусом.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Напиток \"Натахтари\" Лимон и лайм (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-limon-i-laym.jpg", description: "Грузинский газированный напиток со вкусом лимона и лайма.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Напиток \"Натахтари\" Фейхоа (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-feyhoa.jpg", description: "Грузинский газированный напиток со вкусом фейхоа.", calories: 44, protein: 0, fat: 0, carbs: 11 },
  { name: "Добрый Кола", category: Category.OTHER, volumeMl: 330, purchasePrice: 55, caseSize: 24, imageUrl: "/dobriy-kola-jb.jpg", description: "Газированный напиток со вкусом колы.", calories: 42, protein: 0, fat: 0, carbs: 10.5 },
  { name: "Кола (Иран, ж/б)", category: Category.OTHER, volumeMl: 300, purchasePrice: 57, caseSize: 24, imageUrl: "/kola-iran-jb.jpg", description: "Газированный напиток со вкусом колы.", calories: 42, protein: 0, fat: 0, carbs: 10.5 },
  { name: "Квас Бочковой", category: Category.OTHER, volumeMl: 1500, purchasePrice: 79, caseSize: 6, imageUrl: "/kvas-bochkovoy-15l.jpg", description: "Хлебный квас натурального брожения.", calories: 27, protein: 0.2, fat: 0, carbs: 5.5 },
  { name: "Аллея Источников №17", category: Category.OTHER, volumeMl: 1500, purchasePrice: 47, caseSize: 6, imageUrl: "/alleya-istochnikov-17.jpg", description: "Природная минеральная питьевая вода.", calories: 0, protein: 0, fat: 0, carbs: 0 },
  { name: "Букет Чувашии со вкусом лимона", category: Category.OTHER, volumeMl: 500, purchasePrice: 37, caseSize: 12, imageUrl: "/buket-chuvashii-05l.jpg", description: "Газированный напиток с лимонным вкусом.", calories: 38, protein: 0, fat: 0, carbs: 9.5 },
  { name: "Букет Чувашии с ароматом лимона", category: Category.OTHER, volumeMl: 1500, purchasePrice: 85, caseSize: 6, imageUrl: "/buket-chuvashii-15l.jpg", description: "Газированный напиток с лимонным вкусом.", calories: 38, protein: 0, fat: 0, carbs: 9.5 },
  { name: "Раифский источник без газа", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/raifsky-bez-gaza.jpg", description: "Природная питьевая вода без газа.", calories: 0, protein: 0, fat: 0, carbs: 0 },
  { name: "Раифский источник газ.", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/raifsky-gaz.jpg", description: "Природная питьевая вода с газом.", calories: 0, protein: 0, fat: 0, carbs: 0 },
  { name: "Квас Домашний", category: Category.OTHER, volumeMl: 1500, purchasePrice: 98, caseSize: 6, imageUrl: "/kvas-domashniy.jpg", description: "Хлебный квас натурального брожения по домашнему рецепту.", calories: 28, protein: 0.2, fat: 0, carbs: 5.7 },
  { name: "Sprite (ж/б, Иран)", category: Category.OTHER, volumeMl: 300, purchasePrice: 55, caseSize: 24, imageUrl: "/sprite-jb-iran.jpg", description: "Газированный напиток со вкусом лимона и лайма.", calories: 34, protein: 0, fat: 0, carbs: 8.5 },
  { name: "Морс \"Калинов\" Клюква", category: Category.OTHER, volumeMl: 1700, purchasePrice: 98, caseSize: 6, imageUrl: "/kalinov-rodnik-klukva.jpg", description: "Морс из клюквы с высоким содержанием витамина C.", calories: 40, protein: 0.1, fat: 0, carbs: 9.7 },

  // Снеки и сладости
  { name: "Choco Pie 6шт", category: Category.SNACKS, volumeMl: null, purchasePrice: 70, caseSize: 16, imageUrl: "/choco-pie-6pack.jpg", description: "Бисквитное печенье с маршмеллоу в шоколадной глазури.", calories: 440, protein: 5, fat: 22, carbs: 58 },
  { name: "Вафли \"Артековские\"", category: Category.SNACKS, volumeMl: null, weightGrams: 5000, purchasePrice: 1285, caseSize: 1, markup: 20, imageUrl: "/vafli-artekovskie.jpg", description: "Хрустящие вафли с ванильной начинкой.", calories: 520, protein: 5, fat: 28, carbs: 62 },
  { name: "Шоколад молочный \"Алёнка\"", category: Category.SNACKS, volumeMl: null, weightGrams: 75, purchasePrice: 78, caseSize: 16, imageUrl: "/alenka-75g.jpg", description: "Классический молочный шоколад.", calories: 550, protein: 7.5, fat: 35, carbs: 54 },
  { name: "Вафли Zebra с карам. арахис и изюм", category: Category.SNACKS, volumeMl: null, weightGrams: 40, purchasePrice: 33, caseSize: 15, imageUrl: "/vafli-zebra.jpg", description: "Вафли с карамелью, арахисом и изюмом.", calories: 500, protein: 6, fat: 27, carbs: 60 },
  { name: "Twix", category: Category.SNACKS, volumeMl: null, weightGrams: 55, purchasePrice: 46, caseSize: 40, imageUrl: "/twix.jpg", description: "Песочное печенье с карамелью в молочном шоколаде.", calories: 495, protein: 4.7, fat: 24, carbs: 66 },
  { name: "Bounty", category: Category.SNACKS, volumeMl: null, weightGrams: 55, purchasePrice: 46, caseSize: 32, imageUrl: "/bounty.jpg", description: "Кокосовая начинка в молочном шоколаде.", calories: 480, protein: 4, fat: 27, carbs: 55 },
  { name: "Халва подсолнечная", category: Category.SNACKS, volumeMl: null, weightGrams: 5000, purchasePrice: 248, caseSize: 1, imageUrl: "/halva.jpg", description: "Подсолнечная халва с натуральным вкусом.", calories: 516, protein: 11.6, fat: 29.7, carbs: 54 },
  { name: "Alpen Gold с фундуком и изюмом", category: Category.SNACKS, volumeMl: null, weightGrams: 85, purchasePrice: 79, caseSize: 21, imageUrl: "/alpen-gold-fundu-izum.jpg", description: "Молочный шоколад с фундуком и изюмом.", calories: 520, protein: 6.5, fat: 30, carbs: 55 },
  { name: "Alpen Gold с клубнично-йогуртовой начинкой", category: Category.SNACKS, volumeMl: null, weightGrams: 85, purchasePrice: 79, caseSize: 21, imageUrl: "/alpen-gold-klubnika-yogurt.jpg", description: "Молочный шоколад с клубнично-йогуртовой начинкой.", calories: 510, protein: 6, fat: 28, carbs: 57 },
  { name: "Lay's «Бекон»", category: Category.SNACKS, volumeMl: null, weightGrams: 70, purchasePrice: 82, caseSize: 25, markup: 10, imageUrl: "/lays-bekon.jpg", description: "Хрустящие картофельные чипсы со вкусом бекона.", calories: 530, protein: 6, fat: 34, carbs: 50 },
  { name: "Lay's «Сыр»", category: Category.SNACKS, volumeMl: null, weightGrams: 70, purchasePrice: 82, caseSize: 25, markup: 10, imageUrl: "/lays-syr.jpg", description: "Хрустящие картофельные чипсы со вкусом сыра.", calories: 530, protein: 6, fat: 34, carbs: 50 },
  { name: "Lay's «Малосольные огурцы»", category: Category.SNACKS, volumeMl: null, weightGrams: 140, purchasePrice: 143, caseSize: 19, markup: 10, imageUrl: "/lays-ogurcy.jpg", description: "Хрустящие картофельные чипсы со вкусом малосольных огурцов.", calories: 530, protein: 6, fat: 34, carbs: 50 },
  { name: "Lit Energy Chips Sour Cream & Herbs", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-smetana-zelen.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом сметаны и зелени.", calories: 520, protein: 6, fat: 32, carbs: 51 },
  { name: "Lit Energy Chips Paprika", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-paprika.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом паприки.", calories: 520, protein: 6, fat: 32, carbs: 51 },
  { name: "Lit Energy Chips Cheddar Cheese", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-cheddar.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом сыра чеддер.", calories: 525, protein: 6.5, fat: 33, carbs: 50 },
  { name: "Lit Energy Chips Sakhalin Crab", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-krab.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом сахалинского краба.", calories: 520, protein: 6, fat: 32, carbs: 51 },
  { name: "Батончик \"Супер\" нуга и карамель", category: Category.SNACKS, volumeMl: null, weightGrams: 40, purchasePrice: 14, caseSize: 18, markup: 5, imageUrl: "/super-batonchik.jpg", description: "Батончик с нугой и карамелью в шоколаде.", calories: 460, protein: 4, fat: 18, carbs: 70 },
  { name: "M&M's", category: Category.SNACKS, volumeMl: null, weightGrams: 45, purchasePrice: 58, caseSize: 32, markup: 0, imageUrl: "/mms-shokolad.jpg", description: "Молочный шоколад в хрустящей цветной глазури.", calories: 480, protein: 4.6, fat: 20, carbs: 68 },
  { name: "\"Веселики\" кукурузные палочки", category: Category.SNACKS, volumeMl: null, weightGrams: 500, purchasePrice: 135, caseSize: 1, markup: 10, imageUrl: "/veseliki-kukuruz.jpg", description: "Хрустящие кукурузные палочки со сладкой посыпкой.", calories: 450, protein: 6, fat: 18, carbs: 65 },
  { name: "Snickers", category: Category.SNACKS, volumeMl: null, weightGrams: 50, purchasePrice: 46, caseSize: 48, markup: 4, imageUrl: "/snickers.jpg", description: "Батончик с арахисом, нугой и карамелью в шоколаде.", calories: 488, protein: 8.4, fat: 24.7, carbs: 57 },
  { name: "Mars Max", category: Category.SNACKS, volumeMl: null, weightGrams: 81, purchasePrice: 67, caseSize: 24, markup: 10, imageUrl: "/mars-max.jpg", description: "Батончик с нугой и карамелью в молочном шоколаде.", calories: 450, protein: 4, fat: 17, carbs: 70 },

  // Чай и кофе
  { name: "Кофе Жокей \"Голд\" м/у", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 168, caseSize: 12, description: "Растворимый кофе с насыщенным ароматом.", calories: 2, protein: 0.2, fat: 0, carbs: 0.3 },
  { name: "Кофе Жокей \"Импер\" раст.субл. м/у", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 168, caseSize: 12, imageUrl: "/kofe-zhokey-imper.jpg", description: "Сублимированный растворимый кофе с мягким вкусом.", calories: 2, protein: 0.2, fat: 0, carbs: 0.3 },
  { name: "Greenfield Golden Ceylon 25пак", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 72, caseSize: 10, imageUrl: "/greenfield-golden-ceylon.jpg", description: "Чёрный цейлонский чай в пакетиках.", calories: 1, protein: 0, fat: 0, carbs: 0.3 },
  { name: "Greenfield Green Melissa 100пак", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 258, caseSize: 9, markup: 20, imageUrl: "/greenfield-green-melissa.jpg", description: "Зелёный чай с мелиссой в пакетиках.", calories: 1, protein: 0, fat: 0, carbs: 0.2 },
  { name: "Tess Pleasure 25пак", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 60, caseSize: 10, imageUrl: "/tess-plaisir.jpg", description: "Чёрный чай с фруктовыми добавками в пакетиках.", calories: 1, protein: 0, fat: 0, carbs: 0.3 },
  { name: "Принцесса \"Нури\" Высокогорный 100пак. черн.", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 148, caseSize: 18, imageUrl: "/princessa-nuri-vysokogorny.jpg", description: "Чёрный высокогорный чай в пакетиках.", calories: 1, protein: 0, fat: 0, carbs: 0.3 },
  { name: "Кофе \"Нескафе 3в1\" Классик", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 15, purchasePrice: 290, caseSize: 20, imageUrl: "/nescafe-3v1-classic.jpg", description: "Растворимый кофейный напиток 3 в 1 с сахаром и сливками.", calories: 45, protein: 1, fat: 1.5, carbs: 8 },
  { name: "Jacobs Monarch Intense (ст/б)", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 48, purchasePrice: 185, caseSize: 12, markup: 20, imageUrl: "/jacobs-monarch-intense.jpg", description: "Растворимый кофе с насыщенным крепким вкусом.", calories: 2, protein: 0.2, fat: 0, carbs: 0.3 },
  { name: "Кофе \"Черная карта голд\"", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 185, caseSize: 12, markup: 20, imageUrl: "/chernaya-karta-gold.jpg", description: "Растворимый кофе с мягким ароматом.", calories: 2, protein: 0.2, fat: 0, carbs: 0.3 },
  { name: "Кофе \"Суаре\" \"Кофейня на паяхъ\"", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 228, caseSize: 12, markup: 20, imageUrl: "/suare-kofeynya.jpg", description: "Растворимый кофе с насыщенным ароматом.", calories: 2, protein: 0.2, fat: 0, carbs: 0.3 },
  { name: "Кофе Жокей \"Триумф\" раст.субл. м/у", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 168, caseSize: 12, markup: 20, imageUrl: "/zhokey-triumf.jpg", description: "Сублимированный растворимый кофе с мягким вкусом.", calories: 2, protein: 0.2, fat: 0, carbs: 0.3 },

  // Консервы
  { name: "Сардина в т/с с овощ. гарн. ГОСТ (Сохраним Традиции)", category: Category.CANNED, volumeMl: null, weightGrams: 240, purchasePrice: 110, caseSize: 24, imageUrl: "/sardina-v-tomate.jpg", description: "Сардина с овощным гарниром в томатном соусе.", calories: 170, protein: 15, fat: 10, carbs: 5 },
  { name: "Килька в т/с красная банка", category: Category.CANNED, volumeMl: null, purchasePrice: 49, caseSize: 1, imageUrl: "/kilka-v-tomate.jpg", description: "Килька в томатном соусе.", calories: 160, protein: 14, fat: 8, carbs: 6 },
  { name: "Скумбрия в масле (Сохраним традиции)", category: Category.CANNED, volumeMl: null, weightGrams: 240, purchasePrice: 165, caseSize: 24, imageUrl: "/skumbriya-v-masle.jpg", description: "Скумбрия в масле.", calories: 280, protein: 18, fat: 23, carbs: 0 },
  { name: "Сгущенка \"МариМолоко\" 250г", category: Category.CANNED, volumeMl: null, weightGrams: 250, purchasePrice: 52, caseSize: 24, imageUrl: "/sgushenka-marimoloko.jpg", description: "Сгущённое молоко с сахаром по ГОСТ.", calories: 320, protein: 7.2, fat: 8.5, carbs: 56 },
  { name: "Горошек \"Фрау Марта\"", category: Category.CANNED, volumeMl: null, weightGrams: 310, purchasePrice: 68, caseSize: 15, imageUrl: "/frau-marta-goroshek.jpg", description: "Консервированный зелёный горошек.", calories: 55, protein: 5, fat: 0.2, carbs: 8 },
  { name: "Сгущенка \"МариМолоко\" 350г", category: Category.CANNED, volumeMl: null, weightGrams: 350, purchasePrice: 56, caseSize: 24, markup: 15, imageUrl: "/sgushenka-marimoloko-350.jpg", description: "Сгущённое молоко с сахаром по ГОСТ.", calories: 320, protein: 7.2, fat: 8.5, carbs: 56 },
  { name: "Сгущенка \"МариМолоко\" 450г", category: Category.CANNED, volumeMl: null, weightGrams: 450, purchasePrice: 71, caseSize: 30, markup: 10, imageUrl: "/sgushenka-marimoloko-350.jpg", description: "Сгущённое молоко с сахаром по ГОСТ.", calories: 320, protein: 7.2, fat: 8.5, carbs: 56 },
  { name: "Хрен \"Махеевъ\" туба столовый", category: Category.CANNED, volumeMl: null, weightGrams: 100, purchasePrice: 60, caseSize: 15, markup: 10, imageUrl: "/maheev-hren.jpg", description: "Столовый хрен, острая приправа.", calories: 45, protein: 2, fat: 0.2, carbs: 8 },

  // Бакалея
  { name: "Гречка", category: Category.GROCERY, volumeMl: null, weightGrams: 10000, purchasePrice: 500, caseSize: 1, markup: 100, imageUrl: "/grechka-10kg.jpg", description: "Гречневая крупа ядрица.", calories: 343, protein: 12.6, fat: 3.3, carbs: 62 },
  { name: "Рис круглозерный", category: Category.GROCERY, volumeMl: null, weightGrams: 10000, purchasePrice: 585, caseSize: 1, markup: 100, imageUrl: "/ris-kruglozerniy-10kg.jpg", description: "Рис круглозёрный шлифованный.", calories: 344, protein: 7, fat: 1, carbs: 74 },
  { name: "Рис пропаренный", category: Category.GROCERY, volumeMl: null, weightGrams: 3000, purchasePrice: 365, caseSize: 1, markup: 40, imageUrl: "/ris-proparenniy-3kg.jpg", description: "Рис длиннозёрный пропаренный.", calories: 348, protein: 7.5, fat: 1, carbs: 75 },
  { name: "Масло \"Злато\"", category: Category.GROCERY, volumeMl: 800, purchasePrice: 125, caseSize: 15, markup: 20, imageUrl: "/maslo-zlato-08l.jpg", description: "Рафинированное дезодорированное подсолнечное масло.", calories: 900, protein: 0, fat: 99.9, carbs: 0 },
  { name: "Корица молотая", category: Category.GROCERY, volumeMl: null, weightGrams: 10, purchasePrice: 12, caseSize: 150, markup: 10, imageUrl: "/koritsa-molotaya.jpg", description: "Молотая корица, пряность.", calories: 247, protein: 4, fat: 1.2, carbs: 80 },
  { name: "Приправа \"Магия Востока\" овощная универсальная", category: Category.GROCERY, volumeMl: null, weightGrams: 75, purchasePrice: 23, caseSize: 20, markup: 10, imageUrl: "/magiya-vostoka-ovoshnaya.jpg", description: "Универсальная овощная приправа для первых и вторых блюд.", calories: 190, protein: 8, fat: 5, carbs: 28 },
  { name: "Бумага туалетная \"Челны\"", category: Category.GROCERY, volumeMl: null, purchasePrice: 23.5, caseSize: 48, markup: 10, imageUrl: "/bumaga-chelny.jpg", description: "Мягкая трёхслойная туалетная бумага." },
  { name: "Макаронные изделия \"Ситно\" рожки", category: Category.GROCERY, volumeMl: null, weightGrams: 5000, purchasePrice: 268, caseSize: 1, markup: 100, imageUrl: "/sitno-rozhki-5kg.jpg", description: "Макаронные изделия из твёрдых сортов пшеницы.", calories: 344, protein: 10.4, fat: 1.3, carbs: 71 },
  { name: "Соль \"Илецкая\"", category: Category.GROCERY, volumeMl: null, weightGrams: 30000, purchasePrice: 465, caseSize: 1, markup: 200, imageUrl: "/sol-ileckaya.jpg", description: "Природная каменная пищевая соль без добавок, натрий ~39 г на 100 г." },
  { name: "Горох колотый", category: Category.GROCERY, volumeMl: null, weightGrams: 25000, purchasePrice: 900, caseSize: 1, markup: 120, imageUrl: "/goroh-kolotiy.jpg", description: "Горох колотый шлифованный.", calories: 298, protein: 20.5, fat: 1.6, carbs: 49.5 },
  { name: "Лапша \"Биг Ланч\" курица", category: Category.GROCERY, volumeMl: null, weightGrams: 90, purchasePrice: 49, caseSize: 24, markup: 10, imageUrl: "/big-lanch-kuritsa.jpg", description: "Лапша быстрого приготовления со вкусом курицы.", calories: 445, protein: 9, fat: 17, carbs: 63 },
  { name: "Сахар кусковой", category: Category.GROCERY, volumeMl: null, weightGrams: 500, purchasePrice: 54, caseSize: 40, markup: 0, description: "Сахар-рафинад кусковой.", calories: 398, protein: 0, fat: 0, carbs: 99.8 },
  { name: "Сахар", category: Category.GROCERY, volumeMl: null, weightGrams: 250, purchasePrice: 41, caseSize: 40, markup: 0, description: "Сахар-песок.", calories: 398, protein: 0, fat: 0, carbs: 99.8 },
  { name: "Бульон \"Роллтон\" куриный домашний", category: Category.GROCERY, volumeMl: null, weightGrams: 100, purchasePrice: 28, caseSize: 24, markup: 10, imageUrl: "/rollton-bulon-kuriniy.jpg", description: "Концентрат для приготовления бульона со вкусом курицы.", calories: 250, protein: 10, fat: 12, carbs: 25 },

  // Зоотовары
  { name: "Kitekat", category: Category.PET_SUPPLIES, volumeMl: null, weightGrams: 15000, purchasePrice: 3600, caseSize: 1, markup: 100, imageUrl: "/kitekat-15kg.jpg", description: "Сухой корм для взрослых кошек. Гарантированный анализ: белок 30%, жир 10%, клетчатка 3%, влага 10%." },
  { name: "Корм для кошек \"Мурчик\" с индейкой", category: Category.PET_SUPPLIES, volumeMl: null, weightGrams: 75, purchasePrice: 17.5, caseSize: 35, markup: 10, imageUrl: "/murchik-indeyka.jpg", description: "Влажный корм для кошек с индейкой в соусе. Гарантированный анализ: белок 8%, жир 5%, клетчатка 0,5%, влага 82%." },

  // Фрукты и овощи
  { name: "Черешня", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 350, caseSize: 1, markup: 49, imageUrl: "/chereshnya.jpg", description: "Свежая черешня.", calories: 52, protein: 1.1, fat: 0.3, carbs: 11.5 },
  { name: "Нектарины азербайджанские", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 140, caseSize: 1, markup: 39, imageUrl: "/nektariny-azerbaydzhan.jpg", description: "Свежие нектарины.", calories: 44, protein: 1.1, fat: 0.3, carbs: 10 },
  { name: "Томаты розовые", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 70, caseSize: 1, markup: 50, imageUrl: "/tomaty-rozoviye.jpg", description: "Свежие розовые томаты.", calories: 20, protein: 0.9, fat: 0.2, carbs: 3.9 },
  { name: "Огурцы грунтовые", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 90, caseSize: 1, markup: 20, imageUrl: "/ogurtsy-gruntoviye.jpg", description: "Свежие грунтовые огурцы.", calories: 15, protein: 0.8, fat: 0.1, carbs: 2.8 },
  { name: "Картофель", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 45, caseSize: 1, markup: 20, imageUrl: "/kartofel.jpg", description: "Свежий картофель.", calories: 77, protein: 2, fat: 0.1, carbs: 16.3 },
  { name: "Лук", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 45, caseSize: 1, markup: 15, imageUrl: "/luk.jpg", description: "Свежий репчатый лук.", calories: 41, protein: 1.4, fat: 0.1, carbs: 8.2 },
];
