import { Category } from "@/generated/prisma/client";

export const MARKUP = 10;

export function getMarkup(category: Category): number {
  // Энергетики, напитки и чай/кофе — наценка +20₽ вместо стандартных +10₽.
  const MARKUP_20_CATEGORIES: Category[] = [Category.ENERGY, Category.OTHER, Category.COFFEE_TEA];
  return MARKUP_20_CATEGORIES.includes(category) ? 20 : MARKUP;
}

export function computeSellPrice(purchasePrice: number, markup: number): number {
  return purchasePrice + markup;
}

export type SeedProduct = {
  name: string;
  category: Category;
  volumeMl: number | null;
  weightGrams?: number;
  purchasePrice: number;
  caseSize: number;
  imageUrl?: string;
  /** Наценка для конкретного товара, если она отличается от стандартной
   * для его категории (см. getMarkup) — например, когда поставщик даёт
   * разную закупочную цену на похожие товары одной категории. */
  markup?: number;
  /** Короткое описание с пищевой ценностью для карточки товара. */
  description?: string;
};

// Наименования, закупочные цены и размер упаковки — из прайс-листа поставщика (2026-07-03).
// Товар продаётся только целой упаковкой (caseSize шт.), розничной продажи по 1 шт. нет.
// Одинаковые позиции, встречавшиеся в прайсе дважды, объединены в одну строку.
export const seedProducts: SeedProduct[] = [
  // Пиво
  { name: "Балтика №0 белое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 60, caseSize: 24, imageUrl: "/baltika-0-beloe-jb.jpg", description: "Безалкогольное пшеничное пиво, лёгкое и освежающее. На 100 мл: 25 ккал, Б 0,3 г, Ж 0 г, У 5,8 г." },
  { name: "Балтика №0 пшеничное (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 59, caseSize: 24, imageUrl: "/baltika-0-pshenichnoe-jb.jpg", description: "Безалкогольное пшеничное пиво с мягким солодовым вкусом. На 100 мл: 24 ккал, Б 0,3 г, Ж 0 г, У 5,5 г." },
  { name: "Балтика №3 (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 72, caseSize: 24, imageUrl: "/baltika-3-jb.jpg", description: "Классическое светлое пиво. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Балтика №7 мягкое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 72, caseSize: 24, imageUrl: "/baltika-7-myagkoe-jb.jpg", description: "Мягкое экспортное пиво со сбалансированным вкусом. На 100 мл: 47 ккал, Б 0,4 г, Ж 0 г, У 3,6 г." },
  { name: "Балтика №7 (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 83, caseSize: 20, imageUrl: "/baltika-7-stb.jpg", description: "Мягкое экспортное пиво со сбалансированным вкусом. На 100 мл: 47 ккал, Б 0,4 г, Ж 0 г, У 3,6 г." },
  { name: "Балтика №7 (ПЭТ)", category: Category.BEER, volumeMl: null, purchasePrice: 110, caseSize: 9, imageUrl: "/baltika-7-pet.jpg", description: "Мягкое экспортное пиво со сбалансированным вкусом. На 100 мл: 47 ккал, Б 0,4 г, Ж 0 г, У 3,6 г." },
  { name: "Балтика №9 (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 67, caseSize: 24, imageUrl: "/baltika-9-jb.jpg", description: "Крепкое пиво с насыщенным солодовым вкусом. На 100 мл: 62 ккал, Б 0,4 г, Ж 0 г, У 3,8 г." },
  { name: "Балтика №9 (ПЭТ)", category: Category.BEER, volumeMl: 1300, purchasePrice: 127, caseSize: 9, imageUrl: "/baltika-9-pet.jpg", description: "Крепкое пиво с насыщенным солодовым вкусом. На 100 мл: 62 ккал, Б 0,4 г, Ж 0 г, У 3,8 г." },
  { name: "Балтика Кулер (ПЭТ)", category: Category.BEER, volumeMl: 1250, purchasePrice: 128, caseSize: 9, imageUrl: "/baltika-kuler-pet.jpg", description: "Освежающий слабоалкогольный коктейль с фруктовым вкусом. На 100 мл: 48 ккал, Б 0,2 г, Ж 0 г, У 6 г." },
  { name: "Крон Бланш Бьер (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 91, caseSize: 24, imageUrl: "/krone-blanche-jb.jpg", description: "Бельгийское пшеничное пиво с нотами апельсина и кориандра. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,7 г." },
  { name: "Крон Бланш Бьер (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 91, caseSize: 20, imageUrl: "/krone-blanche-stb.jpg", description: "Бельгийское пшеничное пиво с нотами апельсина и кориандра. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,7 г." },
  { name: "Гаррет Черная вишня (ст/б)", category: Category.BEER, volumeMl: 400, purchasePrice: 81, caseSize: 20, imageUrl: "/garret-chernaya-vishnya-stb.jpg", description: "Пивной напиток с ярким вкусом чёрной вишни. На 100 мл: 49 ккал, Б 0,2 г, Ж 0 г, У 6,2 г." },
  { name: "Жатецкий Гусь (ПЭТ)", category: Category.BEER, volumeMl: 1350, purchasePrice: 147, caseSize: 9, imageUrl: "/zateckiy-gus-pet.jpg", description: "Светлое пиво чешского стиля с мягкой горчинкой. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Жатецкий Гусь (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 83, caseSize: 24, imageUrl: "/zateckiy-gus-jb.jpg", description: "Светлое пиво чешского стиля с мягкой горчинкой. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Дон (ПЭТ)", category: Category.BEER, volumeMl: 1500, purchasePrice: 123, caseSize: 9, imageUrl: "/don-pet.jpg", description: "Светлое пиво с классическим солодовым вкусом. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,4 г." },
  { name: "Кулер (ст/б)", category: Category.BEER, volumeMl: 470, purchasePrice: 68, caseSize: 20, imageUrl: "/kuler-stb.jpg", description: "Освежающий слабоалкогольный коктейль с фруктовым вкусом. На 100 мл: 48 ккал, Б 0,2 г, Ж 0 г, У 6 г." },
  { name: "Кулер (ж/б)", category: Category.BEER, volumeMl: 470, purchasePrice: 70, caseSize: 24, imageUrl: "/kuler-jb.jpg", description: "Освежающий слабоалкогольный коктейль с фруктовым вкусом. На 100 мл: 48 ккал, Б 0,2 г, Ж 0 г, У 6 г." },
  { name: "Охота крепкое (ПЭТ)", category: Category.BEER, volumeMl: 1250, purchasePrice: 130, caseSize: 9, imageUrl: "/ohota-krepkoe-pet.jpg", description: "Крепкое пиво с выраженным солодовым вкусом. На 100 мл: 63 ккал, Б 0,4 г, Ж 0 г, У 3,9 г." },
  { name: "Голд Майн Бир (ПЭТ)", category: Category.BEER, volumeMl: 1200, purchasePrice: 112, caseSize: 9, imageUrl: "/gold-mine-beer-pet.jpg", description: "Светлое пиво с лёгкой хмелевой горчинкой. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,4 г." },
  { name: "Бочкарев Холод и Солод светлое (ПЭТ)", category: Category.BEER, volumeMl: 950, purchasePrice: 105, caseSize: 9, imageUrl: "/bochkarev-holod-i-solod-pet.jpg", description: "Светлое пиво с чистым солодовым вкусом. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Бочкарев Живой Розлив светлое (ПЭТ)", category: Category.BEER, volumeMl: 950, purchasePrice: 105, caseSize: 9, imageUrl: "/bochkarev-zhivoi-rozliv-pet.jpg", description: "Непастеризованное светлое пиво живого розлива. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Белый Медведь Светлое (ПЭТ)", category: Category.BEER, volumeMl: 1200, purchasePrice: 115, caseSize: 9, imageUrl: "/belyi-medved-svetloe-pet.jpg", description: "Светлое пиво с мягким вкусом. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,4 г." },
  { name: "Белый Медведь Крепкое (ПЭТ)", category: Category.BEER, volumeMl: 1150, purchasePrice: 135, caseSize: 9, imageUrl: "/belyi-medved-krepkoe-pet.jpg", description: "Крепкое пиво с насыщенным вкусом. На 100 мл: 64 ккал, Б 0,4 г, Ж 0 г, У 4 г." },
  { name: "Эфес Пилсенер (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 82, caseSize: 20, imageUrl: "/efes-pilsener-stb.jpg", description: "Турецкий светлый пилснер с хмелевой горчинкой. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Эсса Солнце на пляже (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 79, caseSize: 24, imageUrl: "/essa-sun-on-beach-stb.jpg", description: "Пивной напиток с ярким тропическим фруктовым вкусом. На 100 мл: 50 ккал, Б 0,2 г, Ж 0 г, У 6,5 г." },
  { name: "Шпатен Мюнхен Хеллес (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 116, caseSize: 20, imageUrl: "/spaten-munchen-stb.jpg", description: "Баварское светлое пиво мюнхенского стиля. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Хугарден Грейпфрут (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 90, caseSize: 20, imageUrl: "/hoegaarden-grapefruit-stb.jpg", description: "Бельгийское пшеничное пиво с грейпфрутовым акцентом. На 100 мл: 46 ккал, Б 0,4 г, Ж 0 г, У 4,8 г." },
  { name: "Хугарден Вишня (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 90, caseSize: 20, imageUrl: "/hoegaarden-vishnya-stb.jpg", description: "Бельгийское пшеничное пиво с вишнёвым акцентом. На 100 мл: 46 ккал, Б 0,4 г, Ж 0 г, У 4,8 г." },
  { name: "Хугарден (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 90, caseSize: 20, imageUrl: "/hoegaarden-stb.jpg", description: "Классическое бельгийское пшеничное пиво с кориандром и апельсиновой цедрой. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,7 г." },
  { name: "Стелла (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 102, caseSize: 20, imageUrl: "/stella-stb.jpg", description: "Бельгийский светлый лагер премиум-класса. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,4 г." },
  { name: "Старый Мельник из Бочонка мягкое (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 74, caseSize: 12, imageUrl: "/stariy-melnik-bochonka-stb.jpg", description: "Мягкое светлое пиво с бархатистым вкусом. На 100 мл: 43 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Редд's (ст/б)", category: Category.BEER, volumeMl: 330, purchasePrice: 82, caseSize: 24, imageUrl: "/redds-stb.jpg", description: "Пивной напиток с яблочным вкусом. На 100 мл: 47 ккал, Б 0,2 г, Ж 0 г, У 6 г." },
  { name: "Мягкий Солод Светлое 4.2% (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 58, caseSize: 12, imageUrl: "/myagkiy-solod-42-stb.jpg", description: "Лёгкое светлое пиво с мягким вкусом. На 100 мл: 41 ккал, Б 0,4 г, Ж 0 г, У 3,2 г." },
  { name: "Миллер (ст/б)", category: Category.BEER, volumeMl: 500, purchasePrice: 72, caseSize: 20, imageUrl: "/miller-stb.jpg", description: "Американский светлый лагер с лёгким хмелевым вкусом. На 100 мл: 43 ккал, Б 0,3 г, Ж 0 г, У 3,2 г." },
  { name: "Корона Экстра (ст/б)", category: Category.BEER, volumeMl: 355, purchasePrice: 118, caseSize: 24, imageUrl: "/corona-extra-stb.jpg", description: "Мексиканское светлое пиво с освежающим вкусом. На 100 мл: 42 ккал, Б 0,3 г, Ж 0 г, У 3,1 г." },
  { name: "Козел Тёмное (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 20, imageUrl: "/kozel-temnoe-stb.jpg", description: "Тёмное чешское пиво с карамельными нотами. На 100 мл: 48 ккал, Б 0,4 г, Ж 0 г, У 4 г." },
  { name: "Козел Светлое (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 20, imageUrl: "/kozel-svetloe-stb.jpg", description: "Светлое чешское пиво с мягкой горчинкой. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Жигули Барное (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 68, caseSize: 20, imageUrl: "/zhiguli-barnoe-stb.jpg", description: "Светлое пиво по классической рецептуре. На 100 мл: 42 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Жигули 1968 (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 64, caseSize: 20, imageUrl: "/zhiguli-1968-stb.jpg", description: "Светлое пиво по рецепту образца 1968 года. На 100 мл: 42 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Доктор Дизель Малина-Лайм (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 77, caseSize: 20, imageUrl: "/dr-diesel-malina-laym-stb.jpg", description: "Пивной напиток со вкусом малины и лайма. На 100 мл: 49 ккал, Б 0,2 г, Ж 0 г, У 6,3 г." },
  { name: "Гринбит (ст/б)", category: Category.BEER, volumeMl: 480, purchasePrice: 75, caseSize: 20, imageUrl: "/grinbit-stb.jpg", description: "Светлое пиво с лёгким освежающим вкусом. На 100 мл: 43 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Гаррет Грейпфрут (ст/б)", category: Category.BEER, volumeMl: 400, purchasePrice: 87, caseSize: 20, imageUrl: "/garret-greypfrut-stb.jpg", description: "Пивной напиток с грейпфрутовым вкусом. На 100 мл: 49 ккал, Б 0,2 г, Ж 0 г, У 6,2 г." },
  { name: "Брамма (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 70, caseSize: 20, imageUrl: "/bramma-stb.jpg", description: "Светлое пиво со сбалансированным вкусом. На 100 мл: 43 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Бочкарев Холод и Солод светлое (ст/б)", category: Category.BEER, volumeMl: 430, purchasePrice: 69, caseSize: 20, imageUrl: "/bochkarev-holod-i-solod-stb.jpg", description: "Светлое пиво с чистым солодовым вкусом. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Бад (ст/б)", category: Category.BEER, volumeMl: 440, purchasePrice: 100, caseSize: 20, imageUrl: "/bad-stb.jpg", description: "Американский светлый лагер с лёгким вкусом. На 100 мл: 43 ккал, Б 0,3 г, Ж 0 г, У 3,2 г." },
  { name: "Амстердам (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 92, caseSize: 20, description: "Светлое пиво голландского стиля. На 100 мл: 44 ккал, Б 0,4 г, Ж 0 г, У 3,4 г." },
  { name: "Эфес Пилсенер (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 80, caseSize: 24, imageUrl: "/efes-pilsener-jb.jpg", description: "Турецкий светлый пилснер с хмелевой горчинкой. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Шпатен (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 118, caseSize: 24, imageUrl: "/spaten-jb.jpg", description: "Баварское светлое пиво мюнхенского стиля. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Мягкий Солод Светлое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 58, caseSize: 12, imageUrl: "/myagkiy-solod-jb.jpg", description: "Лёгкое светлое пиво с мягким вкусом. На 100 мл: 41 ккал, Б 0,4 г, Ж 0 г, У 3,2 г." },
  { name: "Охота крепкое (ж/б)", category: Category.BEER, volumeMl: 430, purchasePrice: 63, caseSize: 24, imageUrl: "/ohota-krepkoe-jb.jpg", description: "Крепкое пиво с выраженным солодовым вкусом. На 100 мл: 63 ккал, Б 0,4 г, Ж 0 г, У 3,9 г." },
  { name: "Жигули Барное (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 68, caseSize: 24, imageUrl: "/zhiguli-barnoe-jb.jpg", description: "Светлое пиво по классической рецептуре. На 100 мл: 42 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Гринбит (ж/б)", category: Category.BEER, volumeMl: 480, purchasePrice: 75, caseSize: 24, imageUrl: "/grinbit-jb.jpg", description: "Светлое пиво с лёгким освежающим вкусом. На 100 мл: 43 ккал, Б 0,4 г, Ж 0 г, У 3,3 г." },
  { name: "Велкопоповицкий Козел Тёмное (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 24, imageUrl: "/kozel-temnoe-jb.jpg", description: "Тёмное чешское пиво с карамельными нотами. На 100 мл: 48 ккал, Б 0,4 г, Ж 0 г, У 4 г." },
  { name: "Велкопоповицкий Козел Светлое (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 88, caseSize: 24, imageUrl: "/kozel-svetloe-jb.jpg", description: "Светлое чешское пиво с мягкой горчинкой. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Бад (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 100, caseSize: 24, imageUrl: "/bad-jb.jpg", description: "Американский светлый лагер с лёгким вкусом. На 100 мл: 43 ккал, Б 0,3 г, Ж 0 г, У 3,2 г." },
  { name: "Ловенбрау (ж/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 82, caseSize: 24, imageUrl: "/lowenbrau-jb.jpg", description: "Баварское светлое пиво с мягким вкусом. На 100 мл: 45 ккал, Б 0,4 г, Ж 0 г, У 3,5 г." },
  { name: "Эсса Ананас Грейпфрут (ст/б)", category: Category.BEER, volumeMl: 450, purchasePrice: 79, caseSize: 20, markup: 10, imageUrl: "/essa-ananas-greypfrut.jpg", description: "Пивной напиток со вкусом ананаса и грейпфрута. На 100 мл: 50 ккал, Б 0,2 г, Ж 0 г, У 6,5 г." },

  // Энергетики
  { name: "Adrenaline Rush Sugar Free (White)", category: Category.ENERGY, volumeMl: 449, purchasePrice: 98, caseSize: 12, imageUrl: "/adrenaline-rush-zero-white.jpg", description: "Энергетик без сахара с кофеином и таурином. На 100 мл: 3 ккал, Б 0 г, Ж 0 г, У 0,5 г, кофеин ~30 мг." },
  { name: "Adrenaline Rush 0,25л", category: Category.ENERGY, volumeMl: 250, purchasePrice: 75, caseSize: 12, imageUrl: "/adrenaline-rush-025-jb.jpg", description: "Классический энергетик с кофеином и таурином. На 100 мл: 48 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Adrenaline Rush", category: Category.ENERGY, volumeMl: 449, purchasePrice: 102, caseSize: 12, imageUrl: "/adrenaline-rush-classic.jpg", description: "Классический энергетик с кофеином и таурином. На 100 мл: 48 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Flash Berry", category: Category.ENERGY, volumeMl: 440, purchasePrice: 63, caseSize: 24, imageUrl: "/flash-yagodniy-jb.jpg", description: "Энергетик с ягодным вкусом. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Flash", category: Category.ENERGY, volumeMl: 1000, purchasePrice: 88, caseSize: 9, imageUrl: "/flash-pet-1l.jpg", description: "Классический энергетический напиток. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Flash 0.5л", category: Category.ENERGY, volumeMl: 500, purchasePrice: 63, caseSize: 20, imageUrl: "/flash-pet-05.jpg", description: "Классический энергетический напиток. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Black Monster Ultra Fantasy", category: Category.ENERGY, volumeMl: 500, purchasePrice: 165, caseSize: 12, imageUrl: "/monster-ultra-black.jpg", description: "Низкокалорийный энергетик с лёгким фруктовым вкусом. На 100 мл: 10 ккал, Б 0,3 г, Ж 0 г, У 2 г, кофеин ~32 мг." },
  { name: "Tornado Storm", category: Category.ENERGY, volumeMl: 450, purchasePrice: 66, caseSize: 12, imageUrl: "/tornado-storm.jpg", description: "Энергетик с ярким фруктовым вкусом. На 100 мл: 47 ккал, Б 0 г, Ж 0 г, У 11,5 г, кофеин ~30 мг." },
  { name: "Tornado Mango", category: Category.ENERGY, volumeMl: 1000, purchasePrice: 89, caseSize: 6, imageUrl: "/tornado-mango-pet.jpg", description: "Энергетик со вкусом манго. На 100 мл: 47 ккал, Б 0 г, Ж 0 г, У 11,5 г, кофеин ~30 мг." },
  { name: "Mountain Dew 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 95, caseSize: 9, imageUrl: "/mountain-dew-pet-1l.jpg", description: "Газированный цитрусовый напиток с кофеином. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11,5 г." },
  { name: "Mountain Dew 0.5л", category: Category.OTHER, volumeMl: 500, purchasePrice: 74, caseSize: 12, imageUrl: "/mountain-dew-pet-05.jpg", description: "Газированный цитрусовый напиток с кофеином. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11,5 г." },
  { name: "Mountain Dew", category: Category.OTHER, volumeMl: 330, purchasePrice: 64, caseSize: 24, imageUrl: "/mountain-dew-jb.jpg", description: "Газированный цитрусовый напиток с кофеином. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11,5 г." },
  { name: "Power Torr Mango", category: Category.ENERGY, volumeMl: 1000, purchasePrice: 90, caseSize: 6, imageUrl: "/power-torr-mango-pet.jpg", description: "Энергетик со вкусом манго. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Power Torr Blue", category: Category.ENERGY, volumeMl: 500, purchasePrice: 59, caseSize: 12, imageUrl: "/power-torr-siniy-pet.jpg", description: "Энергетик с ярким освежающим вкусом. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Peach", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-peach.jpg", description: "Энергетик с персиковым вкусом. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Raspberry Crush", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-malina-crush.jpg", description: "Энергетик с малиновым вкусом. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Berry Coconut", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-berry-coconut.jpg", description: "Энергетик со вкусом ягод и кокоса. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Classic", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-classic.jpg", description: "Классический энергетический напиток. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Original", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-original.jpg", description: "Классический энергетический напиток. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Blueberry", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-blueberry.jpg", description: "Энергетик с черничным вкусом. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Citrus Punch", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-citrus-punch.jpg", description: "Энергетик с цитрусовым вкусом. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Lit Energy Strawberry Bubblegum", category: Category.ENERGY, volumeMl: 450, purchasePrice: 73, caseSize: 12, imageUrl: "/lit-energy-strawberry-bubblegum.jpg", description: "Энергетик со вкусом клубничной жвачки. На 100 мл: 45 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Volt Гуава", category: Category.ENERGY, volumeMl: 450, purchasePrice: 74, caseSize: 24, imageUrl: "/volt-guava-jb.jpg", description: "Энергетик со вкусом гуавы. На 100 мл: 46 ккал, Б 0 г, Ж 0 г, У 11 г, кофеин ~30 мг." },
  { name: "Gorilla Lychee & Pear", category: Category.ENERGY, volumeMl: 450, purchasePrice: 78, caseSize: 24, imageUrl: "/gorilla-lychee-pear-jb.jpg", description: "Энергетик со вкусом личи и груши. На 100 мл: 47 ккал, Б 0 г, Ж 0 г, У 11,5 г, кофеин ~30 мг." },
  { name: "Flash Ultra", category: Category.ENERGY, volumeMl: 450, purchasePrice: 63, caseSize: 24, imageUrl: "/flesh-ultra-jb.jpg", description: "Низкокалорийный энергетик Ultra. На 100 мл: 12 ккал, Б 0,3 г, Ж 0 г, У 2,5 г, кофеин ~30 мг." },
  { name: "Burn Watermelon Sugar Free", category: Category.ENERGY, volumeMl: 500, purchasePrice: 88, caseSize: 12, imageUrl: "/burn-arbuz.jpg", description: "Энергетик без сахара со вкусом арбуза. На 100 мл: 3 ккал, Б 0 г, Ж 0 г, У 0,5 г, кофеин ~30 мг." },
  { name: "Black Monster Ultra White", category: Category.ENERGY, volumeMl: 500, purchasePrice: 160, caseSize: 12, imageUrl: "/black-monster-ultra-white.jpg", description: "Низкокалорийный энергетик с лёгким освежающим вкусом. На 100 мл: 10 ккал, Б 0,3 г, Ж 0 г, У 2 г, кофеин ~32 мг." },

  // Напитки
  { name: "Добрый Pulpy Апельсин 0,45л", category: Category.OTHER, volumeMl: 450, purchasePrice: 57, caseSize: 12, imageUrl: "/dobriy-pulpy-apelsin.jpg", description: "Сокосодержащий напиток с мякотью апельсина. На 100 мл: 48 ккал, Б 0,2 г, Ж 0 г, У 11,5 г." },
  { name: "Мохито клубничный", category: Category.OTHER, volumeMl: 500, purchasePrice: 61, caseSize: 24, imageUrl: "/mohito-klubnichniy-jb.jpg", description: "Газированный напиток со вкусом клубничного мохито. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 10,5 г." },
  { name: "Добрый Апельсин/Фанта 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 75, caseSize: 12, imageUrl: "/dobriy-fanta-pet.jpg", description: "Газированный напиток с апельсиновым вкусом. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Добрый Фанта", category: Category.OTHER, volumeMl: 500, purchasePrice: 54, caseSize: 24, imageUrl: "/dobriy-fanta-pet.jpg", description: "Газированный напиток с апельсиновым вкусом. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Фанта", category: Category.OTHER, volumeMl: 330, purchasePrice: 55, caseSize: 12, imageUrl: "/fanta-jb.jpg", description: "Газированный напиток с апельсиновым вкусом. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Кока-Кола классическая 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 59, caseSize: 9, imageUrl: "/koka-kola-1l.jpg", description: "Классический газированный напиток кола. На 100 мл: 42 ккал, Б 0 г, Ж 0 г, У 10,6 г." },
  { name: "Кока-Кола классическая 2л", category: Category.OTHER, volumeMl: 2000, purchasePrice: 80, caseSize: 6, imageUrl: "/koka-kola-2l.jpg", description: "Классический газированный напиток кола. На 100 мл: 42 ккал, Б 0 г, Ж 0 г, У 10,6 г." },
  { name: "Кола (Иран, ст/б)", category: Category.OTHER, volumeMl: 330, purchasePrice: 68, caseSize: 15, imageUrl: "/kola-iran-stb.jpg", description: "Газированный напиток со вкусом колы. На 100 мл: 42 ккал, Б 0 г, Ж 0 г, У 10,5 г." },
  { name: "Пепси 2л", category: Category.OTHER, volumeMl: 2000, purchasePrice: 85, caseSize: 6, imageUrl: "/pepsi-2l.jpg", description: "Газированный напиток со вкусом колы. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Фанта 2л", category: Category.OTHER, volumeMl: 2000, purchasePrice: 85, caseSize: 6, imageUrl: "/fanta-2l.jpg", description: "Газированный напиток с апельсиновым вкусом. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Пепси 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 55, caseSize: 12, imageUrl: "/pepsi-1l.jpg", description: "Газированный напиток со вкусом колы. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Квас \"Вятский Хлебный\"", category: Category.OTHER, volumeMl: 1500, purchasePrice: 105, caseSize: 6, imageUrl: "/kvas-vyatskiy-hlebniy.jpg", description: "Традиционный хлебный квас натурального брожения. На 100 мл: 27 ккал, Б 0,2 г, Ж 0 г, У 5,5 г." },
  { name: "Фанта 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 58, caseSize: 12, imageUrl: "/fanta-1l.jpg", description: "Газированный напиток с апельсиновым вкусом. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Спрайт 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 58, caseSize: 12, imageUrl: "/sprite-1l.jpg", description: "Газированный напиток со вкусом лимона и лайма. На 100 мл: 34 ккал, Б 0 г, Ж 0 г, У 8,5 г." },
  { name: "Вода \"Сестрица\" природная газ. 1.5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 35, caseSize: 6, imageUrl: "/sestritsa-gaz-15l.jpg", description: "Природная питьевая вода с газом, без добавок. На 100 мл: 0 ккал." },
  { name: "Вода \"Сестрица\" природная негаз. 1.5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 35, caseSize: 6, imageUrl: "/sestritsa-negaz-15l.jpg", description: "Природная питьевая вода без газа и добавок. На 100 мл: 0 ккал." },
  { name: "Вода \"Сестрица\" б/г 0.5л", category: Category.OTHER, volumeMl: 500, purchasePrice: 25, caseSize: 12, imageUrl: "/sestritsa-bg-05l.jpg", description: "Природная питьевая вода без газа и добавок. На 100 мл: 0 ккал." },
  { name: "Сок \"Джу100\" Яблочно-грушевый 1л", category: Category.OTHER, volumeMl: 1000, purchasePrice: 54, caseSize: 12, imageUrl: "/dju100-yabloko-grusha.jpg", description: "Сок прямого отжима из яблок и груш. На 100 мл: 46 ккал, Б 0,3 г, Ж 0 г, У 11 г." },
  { name: "Напиток \"Ярмарка\" Лимонад 1.5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-limonad.jpg", description: "Газированный лимонад с освежающим вкусом. На 100 мл: 40 ккал, Б 0 г, Ж 0 г, У 10 г." },
  { name: "Напиток \"Ярмарка\" Тархун 1.5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-tarhun.jpg", description: "Газированный напиток со вкусом эстрагона. На 100 мл: 40 ккал, Б 0 г, Ж 0 г, У 10 г." },
  { name: "Напиток \"Ярмарка\" Мохито 1.5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-mohito.jpg", description: "Газированный напиток со вкусом мохито. На 100 мл: 40 ккал, Б 0 г, Ж 0 г, У 10 г." },
  { name: "Напиток \"Ярмарка\" Клубника 1.5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/yarmarka-klubnika.jpg", description: "Газированный напиток с клубничным вкусом. На 100 мл: 40 ккал, Б 0 г, Ж 0 г, У 10 г." },
  { name: "Напиток \"Натахтари\" Тархун (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-tarhun.jpg", description: "Грузинский газированный напиток со вкусом эстрагона. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Напиток \"Натахтари\" Груша (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-grusha.jpg", description: "Грузинский газированный напиток с грушевым вкусом. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Напиток \"Натахтари\" Лимон и лайм (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-limon-i-laym.jpg", description: "Грузинский газированный напиток со вкусом лимона и лайма. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Напиток \"Натахтари\" Фейхоа (ст/б)", category: Category.OTHER, volumeMl: 500, purchasePrice: 90, caseSize: 20, imageUrl: "/natahtari-feyhoa.jpg", description: "Грузинский газированный напиток со вкусом фейхоа. На 100 мл: 44 ккал, Б 0 г, Ж 0 г, У 11 г." },
  { name: "Добрый Кола", category: Category.OTHER, volumeMl: 330, purchasePrice: 55, caseSize: 24, imageUrl: "/dobriy-kola-jb.jpg", description: "Газированный напиток со вкусом колы. На 100 мл: 42 ккал, Б 0 г, Ж 0 г, У 10,5 г." },
  { name: "Кола (Иран, ж/б)", category: Category.OTHER, volumeMl: 300, purchasePrice: 57, caseSize: 24, imageUrl: "/kola-iran-jb.jpg", description: "Газированный напиток со вкусом колы. На 100 мл: 42 ккал, Б 0 г, Ж 0 г, У 10,5 г." },
  { name: "Квас Бочковой 1,5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 79, caseSize: 6, imageUrl: "/kvas-bochkovoy-15l.jpg", description: "Хлебный квас натурального брожения. На 100 мл: 27 ккал, Б 0,2 г, Ж 0 г, У 5,5 г." },
  { name: "Аллея Источников №17", category: Category.OTHER, volumeMl: 1500, purchasePrice: 47, caseSize: 6, imageUrl: "/alleya-istochnikov-17.jpg", description: "Природная минеральная питьевая вода. На 100 мл: 0 ккал." },
  { name: "Букет Чувашии со вкусом лимона 0,5л", category: Category.OTHER, volumeMl: 500, purchasePrice: 37, caseSize: 12, imageUrl: "/buket-chuvashii-05l.jpg", description: "Газированный напиток с лимонным вкусом. На 100 мл: 38 ккал, Б 0 г, Ж 0 г, У 9,5 г." },
  { name: "Букет Чувашии с ароматом лимона 1,5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 85, caseSize: 6, imageUrl: "/buket-chuvashii-15l.jpg", description: "Газированный напиток с лимонным вкусом. На 100 мл: 38 ккал, Б 0 г, Ж 0 г, У 9,5 г." },
  { name: "Раифский источник без газа 1,5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/raifsky-bez-gaza.jpg", description: "Природная питьевая вода без газа. На 100 мл: 0 ккал." },
  { name: "Раифский источник газ. 1,5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 37, caseSize: 6, imageUrl: "/raifsky-gaz.jpg", description: "Природная питьевая вода с газом. На 100 мл: 0 ккал." },
  { name: "Квас Домашний 1,5л", category: Category.OTHER, volumeMl: 1500, purchasePrice: 98, caseSize: 6, imageUrl: "/kvas-domashniy.jpg", description: "Хлебный квас натурального брожения по домашнему рецепту. На 100 мл: 28 ккал, Б 0,2 г, Ж 0 г, У 5,7 г." },
  { name: "Спрайт (ж/б, Иран)", category: Category.OTHER, volumeMl: 300, purchasePrice: 55, caseSize: 24, imageUrl: "/sprite-jb-iran.jpg", description: "Газированный напиток со вкусом лимона и лайма. На 100 мл: 34 ккал, Б 0 г, Ж 0 г, У 8,5 г." },
  { name: "Морс \"Калинов\" Клюква", category: Category.OTHER, volumeMl: 1700, purchasePrice: 98, caseSize: 6, imageUrl: "/kalinov-rodnik-klukva.jpg", description: "Морс из клюквы с высоким содержанием витамина C. На 100 мл: 40 ккал, Б 0,1 г, Ж 0 г, У 9,7 г." },

  // Снеки и сладости
  { name: "Чоко Пай 6шт", category: Category.SNACKS, volumeMl: null, purchasePrice: 70, caseSize: 16, imageUrl: "/choco-pie-6pack.jpg", description: "Бисквитное печенье с маршмеллоу в шоколадной глазури. На 100 г: 440 ккал, Б 5 г, Ж 22 г, У 58 г." },
  { name: "Вафли \"Артековские\"", category: Category.SNACKS, volumeMl: null, weightGrams: 5000, purchasePrice: 1285, caseSize: 1, markup: 20, imageUrl: "/vafli-artekovskie.jpg", description: "Хрустящие вафли с ванильной начинкой. На 100 г: 520 ккал, Б 5 г, Ж 28 г, У 62 г." },
  { name: "Шоколад молочный \"Алёнка\"", category: Category.SNACKS, volumeMl: null, weightGrams: 75, purchasePrice: 78, caseSize: 16, imageUrl: "/alenka-75g.jpg", description: "Классический молочный шоколад. На 100 г: 550 ккал, Б 7,5 г, Ж 35 г, У 54 г." },
  { name: "Вафли \"Зебра\" с карам. арахис и изюм", category: Category.SNACKS, volumeMl: null, weightGrams: 40, purchasePrice: 33, caseSize: 15, imageUrl: "/vafli-zebra.jpg", description: "Вафли с карамелью, арахисом и изюмом. На 100 г: 500 ккал, Б 6 г, Ж 27 г, У 60 г." },
  { name: "Печенье Твикс", category: Category.SNACKS, volumeMl: null, weightGrams: 55, purchasePrice: 46, caseSize: 40, imageUrl: "/twix.jpg", description: "Песочное печенье с карамелью в молочном шоколаде. На 100 г: 495 ккал, Б 4,7 г, Ж 24 г, У 66 г." },
  { name: "Конфета \"Баунти\"", category: Category.SNACKS, volumeMl: null, weightGrams: 55, purchasePrice: 46, caseSize: 32, imageUrl: "/bounty.jpg", description: "Кокосовая начинка в молочном шоколаде. На 100 г: 480 ккал, Б 4 г, Ж 27 г, У 55 г." },
  { name: "Халва подсолнечная", category: Category.SNACKS, volumeMl: null, weightGrams: 5000, purchasePrice: 248, caseSize: 1, imageUrl: "/halva.jpg", description: "Подсолнечная халва с натуральным вкусом. На 100 г: 516 ккал, Б 11,6 г, Ж 29,7 г, У 54 г." },
  { name: "Шоколад \"Альпен Гольд\" с фундуком и изюмом", category: Category.SNACKS, volumeMl: null, weightGrams: 85, purchasePrice: 79, caseSize: 21, imageUrl: "/alpen-gold-fundu-izum.jpg", description: "Молочный шоколад с фундуком и изюмом. На 100 г: 520 ккал, Б 6,5 г, Ж 30 г, У 55 г." },
  { name: "Шоколад \"Альпен Гольд\" с клубнично-йогуртовой начинкой", category: Category.SNACKS, volumeMl: null, weightGrams: 85, purchasePrice: 79, caseSize: 21, imageUrl: "/alpen-gold-klubnika-yogurt.jpg", description: "Молочный шоколад с клубнично-йогуртовой начинкой. На 100 г: 510 ккал, Б 6 г, Ж 28 г, У 57 г." },
  { name: "Чипсы \"Лейс\" бекон", category: Category.SNACKS, volumeMl: null, weightGrams: 70, purchasePrice: 82, caseSize: 25, markup: 10, imageUrl: "/lays-bekon.jpg", description: "Хрустящие картофельные чипсы со вкусом бекона. На 100 г: 530 ккал, Б 6 г, Ж 34 г, У 50 г." },
  { name: "Чипсы \"Лейс\" сыр", category: Category.SNACKS, volumeMl: null, weightGrams: 70, purchasePrice: 82, caseSize: 25, markup: 10, imageUrl: "/lays-syr.jpg", description: "Хрустящие картофельные чипсы со вкусом сыра. На 100 г: 530 ккал, Б 6 г, Ж 34 г, У 50 г." },
  { name: "Чипсы \"Лейс\" малосольные огурцы", category: Category.SNACKS, volumeMl: null, weightGrams: 140, purchasePrice: 143, caseSize: 19, markup: 10, imageUrl: "/lays-ogurcy.jpg", description: "Хрустящие картофельные чипсы со вкусом малосольных огурцов. На 100 г: 530 ккал, Б 6 г, Ж 34 г, У 50 г." },
  { name: "Lit Energy Chips Sour Cream & Herbs", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-smetana-zelen.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом сметаны и зелени. На 100 г: 520 ккал, Б 6 г, Ж 32 г, У 51 г." },
  { name: "Lit Energy Chips Paprika", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-paprika.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом паприки. На 100 г: 520 ккал, Б 6 г, Ж 32 г, У 51 г." },
  { name: "Lit Energy Chips Cheddar Cheese", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-cheddar.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом сыра чеддер. На 100 г: 525 ккал, Б 6,5 г, Ж 33 г, У 50 г." },
  { name: "Lit Energy Chips Sakhalin Crab", category: Category.SNACKS, volumeMl: null, weightGrams: 120, purchasePrice: 126, caseSize: 1, markup: 20, imageUrl: "/lit-energy-chips-krab.jpg", description: "Рифлёные чипсы из натурального картофеля со вкусом сахалинского краба. На 100 г: 520 ккал, Б 6 г, Ж 32 г, У 51 г." },
  { name: "Батончик \"Супер\" нуга и карамель", category: Category.SNACKS, volumeMl: null, weightGrams: 40, purchasePrice: 14, caseSize: 18, markup: 5, imageUrl: "/super-batonchik.jpg", description: "Батончик с нугой и карамелью в шоколаде. На 100 г: 460 ккал, Б 4 г, Ж 18 г, У 70 г." },
  { name: "M&M's шоколад", category: Category.SNACKS, volumeMl: null, weightGrams: 45, purchasePrice: 58, caseSize: 32, markup: 0, imageUrl: "/mms-shokolad.jpg", description: "Молочный шоколад в хрустящей цветной глазури. На 100 г: 480 ккал, Б 4,6 г, Ж 20 г, У 68 г." },
  { name: "\"Веселики\" кукурузные палочки", category: Category.SNACKS, volumeMl: null, weightGrams: 500, purchasePrice: 135, caseSize: 1, markup: 10, imageUrl: "/veseliki-kukuruz.jpg", description: "Хрустящие кукурузные палочки со сладкой посыпкой. На 100 г: 450 ккал, Б 6 г, Ж 18 г, У 65 г." },
  { name: "Сникерс", category: Category.SNACKS, volumeMl: null, weightGrams: 50, purchasePrice: 46, caseSize: 48, markup: 4, imageUrl: "/snickers.jpg", description: "Батончик с арахисом, нугой и карамелью в шоколаде. На 100 г: 488 ккал, Б 8,4 г, Ж 24,7 г, У 57 г." },
  { name: "Марс Макс", category: Category.SNACKS, volumeMl: null, weightGrams: 81, purchasePrice: 67, caseSize: 24, markup: 10, imageUrl: "/mars-max.jpg", description: "Батончик с нугой и карамелью в молочном шоколаде. На 100 г: 450 ккал, Б 4 г, Ж 17 г, У 70 г." },

  // Чай и кофе
  { name: "Кофе Жокей \"Голд\" м/у", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 168, caseSize: 12, description: "Растворимый кофе с насыщенным ароматом. На 100 мл готового напитка: 2 ккал, Б 0,2 г, Ж 0 г, У 0,3 г." },
  { name: "Кофе Жокей \"Импер\" раст.субл. м/у", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 168, caseSize: 12, imageUrl: "/kofe-zhokey-imper.jpg", description: "Сублимированный растворимый кофе с мягким вкусом. На 100 мл готового напитка: 2 ккал, Б 0,2 г, Ж 0 г, У 0,3 г." },
  { name: "Гринфилд \"Голден Цейлон\" 25пак черн.", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 72, caseSize: 10, imageUrl: "/greenfield-golden-ceylon.jpg", description: "Чёрный цейлонский чай в пакетиках. На 100 мл готового напитка: 1 ккал, Б 0 г, Ж 0 г, У 0,3 г." },
  { name: "Гринфилд \"Грин Мелисса\" 100пак", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 258, caseSize: 9, markup: 20, imageUrl: "/greenfield-green-melissa.jpg", description: "Зелёный чай с мелиссой в пакетиках. На 100 мл готового напитка: 1 ккал, Б 0 г, Ж 0 г, У 0,2 г." },
  { name: "Тесс \"Плеже\" 25пак черн. с доб.", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 60, caseSize: 10, imageUrl: "/tess-plaisir.jpg", description: "Чёрный чай с фруктовыми добавками в пакетиках. На 100 мл готового напитка: 1 ккал, Б 0 г, Ж 0 г, У 0,3 г." },
  { name: "Принцесса \"Нури\" Высокогорный 100пак. черн.", category: Category.COFFEE_TEA, volumeMl: null, purchasePrice: 148, caseSize: 18, imageUrl: "/princessa-nuri-vysokogorny.jpg", description: "Чёрный высокогорный чай в пакетиках. На 100 мл готового напитка: 1 ккал, Б 0 г, Ж 0 г, У 0,3 г." },
  { name: "Кофе \"Нескафе 3в1\" Классик", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 15, purchasePrice: 290, caseSize: 20, imageUrl: "/nescafe-3v1-classic.jpg", description: "Растворимый кофейный напиток 3 в 1 с сахаром и сливками. На 100 мл готового напитка: 45 ккал, Б 1 г, Ж 1,5 г, У 8 г." },
  { name: "Кофе \"Якобс Монарх Интенс\" (ст/б)", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 48, purchasePrice: 185, caseSize: 12, markup: 20, imageUrl: "/jacobs-monarch-intense.jpg", description: "Растворимый кофе с насыщенным крепким вкусом. На 100 мл готового напитка: 2 ккал, Б 0,2 г, Ж 0 г, У 0,3 г." },
  { name: "Кофе \"Черная карта голд\"", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 185, caseSize: 12, markup: 20, imageUrl: "/chernaya-karta-gold.jpg", description: "Растворимый кофе с мягким ароматом. На 100 мл готового напитка: 2 ккал, Б 0,2 г, Ж 0 г, У 0,3 г." },
  { name: "Кофе \"Суаре\" \"Кофейня на паяхъ\"", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 228, caseSize: 12, markup: 20, imageUrl: "/suare-kofeynya.jpg", description: "Растворимый кофе с насыщенным ароматом. На 100 мл готового напитка: 2 ккал, Б 0,2 г, Ж 0 г, У 0,3 г." },
  { name: "Кофе Жокей \"Триумф\" раст.субл. м/у", category: Category.COFFEE_TEA, volumeMl: null, weightGrams: 75, purchasePrice: 168, caseSize: 12, markup: 20, imageUrl: "/zhokey-triumf.jpg", description: "Сублимированный растворимый кофе с мягким вкусом. На 100 мл готового напитка: 2 ккал, Б 0,2 г, Ж 0 г, У 0,3 г." },

  // Консервы
  { name: "Сардина в т/с с овощ. гарн. ГОСТ (Сохраним Традиции)", category: Category.CANNED, volumeMl: null, weightGrams: 240, purchasePrice: 110, caseSize: 24, imageUrl: "/sardina-v-tomate.jpg", description: "Сардина с овощным гарниром в томатном соусе. На 100 г: 170 ккал, Б 15 г, Ж 10 г, У 5 г." },
  { name: "Килька в т/с красная банка", category: Category.CANNED, volumeMl: null, purchasePrice: 49, caseSize: 1, imageUrl: "/kilka-v-tomate.jpg", description: "Килька в томатном соусе. На 100 г: 160 ккал, Б 14 г, Ж 8 г, У 6 г." },
  { name: "Скумбрия в масле (Сохраним традиции)", category: Category.CANNED, volumeMl: null, weightGrams: 240, purchasePrice: 165, caseSize: 24, imageUrl: "/skumbriya-v-masle.jpg", description: "Скумбрия в масле. На 100 г: 280 ккал, Б 18 г, Ж 23 г, У 0 г." },
  { name: "Сгущенка \"МариМолоко\" 250г", category: Category.CANNED, volumeMl: null, weightGrams: 250, purchasePrice: 52, caseSize: 24, imageUrl: "/sgushenka-marimoloko.jpg", description: "Сгущённое молоко с сахаром по ГОСТ. На 100 г: 320 ккал, Б 7,2 г, Ж 8,5 г, У 56 г." },
  { name: "Горошек \"Фрау Марта\"", category: Category.CANNED, volumeMl: null, weightGrams: 310, purchasePrice: 68, caseSize: 15, imageUrl: "/frau-marta-goroshek.jpg", description: "Консервированный зелёный горошек. На 100 г: 55 ккал, Б 5 г, Ж 0,2 г, У 8 г." },
  { name: "Сгущенка \"МариМолоко\" 350г", category: Category.CANNED, volumeMl: null, weightGrams: 350, purchasePrice: 56, caseSize: 24, markup: 15, imageUrl: "/sgushenka-marimoloko-350.jpg", description: "Сгущённое молоко с сахаром по ГОСТ. На 100 г: 320 ккал, Б 7,2 г, Ж 8,5 г, У 56 г." },
  { name: "Сгущенка \"МариМолоко\" 450г", category: Category.CANNED, volumeMl: null, weightGrams: 450, purchasePrice: 71, caseSize: 30, markup: 10, imageUrl: "/sgushenka-marimoloko-350.jpg", description: "Сгущённое молоко с сахаром по ГОСТ. На 100 г: 320 ккал, Б 7,2 г, Ж 8,5 г, У 56 г." },
  { name: "Хрен \"Махеевъ\" туба столовый", category: Category.CANNED, volumeMl: null, weightGrams: 100, purchasePrice: 60, caseSize: 15, markup: 10, imageUrl: "/maheev-hren.jpg", description: "Столовый хрен, острая приправа. На 100 г: 45 ккал, Б 2 г, Ж 0,2 г, У 8 г." },

  // Бакалея
  { name: "Гречка", category: Category.GROCERY, volumeMl: null, weightGrams: 10000, purchasePrice: 500, caseSize: 1, markup: 100, imageUrl: "/grechka-10kg.jpg", description: "Гречневая крупа ядрица. На 100 г: 343 ккал, Б 12,6 г, Ж 3,3 г, У 62 г." },
  { name: "Рис круглозерный", category: Category.GROCERY, volumeMl: null, weightGrams: 10000, purchasePrice: 585, caseSize: 1, markup: 100, imageUrl: "/ris-kruglozerniy-10kg.jpg", description: "Рис круглозёрный шлифованный. На 100 г: 344 ккал, Б 7 г, Ж 1 г, У 74 г." },
  { name: "Рис пропаренный", category: Category.GROCERY, volumeMl: null, weightGrams: 3000, purchasePrice: 365, caseSize: 1, markup: 40, imageUrl: "/ris-proparenniy-3kg.jpg", description: "Рис длиннозёрный пропаренный. На 100 г: 348 ккал, Б 7,5 г, Ж 1 г, У 75 г." },
  { name: "Масло \"Злато\"", category: Category.GROCERY, volumeMl: 800, purchasePrice: 125, caseSize: 15, markup: 20, imageUrl: "/maslo-zlato-08l.jpg", description: "Рафинированное дезодорированное подсолнечное масло. На 100 г: 900 ккал, Б 0 г, Ж 99,9 г, У 0 г." },
  { name: "Корица молотая", category: Category.GROCERY, volumeMl: null, weightGrams: 10, purchasePrice: 12, caseSize: 150, markup: 10, imageUrl: "/koritsa-molotaya.jpg", description: "Молотая корица, пряность. На 100 г: 247 ккал, Б 4 г, Ж 1,2 г, У 80 г." },
  { name: "Приправа \"Магия Востока\" овощная универсальная", category: Category.GROCERY, volumeMl: null, weightGrams: 75, purchasePrice: 23, caseSize: 20, markup: 10, imageUrl: "/magiya-vostoka-ovoshnaya.jpg", description: "Универсальная овощная приправа для первых и вторых блюд. На 100 г: 190 ккал, Б 8 г, Ж 5 г, У 28 г." },
  { name: "Бумага туалетная \"Челны\"", category: Category.GROCERY, volumeMl: null, purchasePrice: 23.5, caseSize: 48, markup: 10, imageUrl: "/bumaga-chelny.jpg", description: "Мягкая трёхслойная туалетная бумага." },
  { name: "Макаронные изделия \"Ситно\" рожки", category: Category.GROCERY, volumeMl: null, weightGrams: 5000, purchasePrice: 268, caseSize: 1, markup: 100, imageUrl: "/sitno-rozhki-5kg.jpg", description: "Макаронные изделия из твёрдых сортов пшеницы. На 100 г: 344 ккал, Б 10,4 г, Ж 1,3 г, У 71 г." },
  { name: "Соль \"Илецкая\"", category: Category.GROCERY, volumeMl: null, weightGrams: 30000, purchasePrice: 465, caseSize: 1, markup: 200, imageUrl: "/sol-ileckaya.jpg", description: "Природная каменная пищевая соль без добавок. На 100 г: 0 ккал, натрий ~39 г." },
  { name: "Горох колотый", category: Category.GROCERY, volumeMl: null, weightGrams: 25000, purchasePrice: 900, caseSize: 1, markup: 120, imageUrl: "/goroh-kolotiy.jpg", description: "Горох колотый шлифованный. На 100 г: 298 ккал, Б 20,5 г, Ж 1,6 г, У 49,5 г." },
  { name: "Лапша \"Биг Ланч\" курица", category: Category.GROCERY, volumeMl: null, weightGrams: 90, purchasePrice: 49, caseSize: 24, markup: 10, imageUrl: "/big-lanch-kuritsa.jpg", description: "Лапша быстрого приготовления со вкусом курицы. На 100 г: 445 ккал, Б 9 г, Ж 17 г, У 63 г." },
  { name: "Сахар кусковой", category: Category.GROCERY, volumeMl: null, weightGrams: 500, purchasePrice: 54, caseSize: 40, markup: 0, description: "Сахар-рафинад кусковой. На 100 г: 398 ккал, Б 0 г, Ж 0 г, У 99,8 г." },
  { name: "Сахар", category: Category.GROCERY, volumeMl: null, weightGrams: 250, purchasePrice: 41, caseSize: 40, markup: 0, description: "Сахар-песок. На 100 г: 398 ккал, Б 0 г, Ж 0 г, У 99,8 г." },
  { name: "Бульон \"Роллтон\" куриный домашний", category: Category.GROCERY, volumeMl: null, weightGrams: 100, purchasePrice: 28, caseSize: 24, markup: 10, imageUrl: "/rollton-bulon-kuriniy.jpg", description: "Концентрат для приготовления бульона со вкусом курицы. На 100 г: 250 ккал, Б 10 г, Ж 12 г, У 25 г." },

  // Зоотовары
  { name: "Сухой корм \"Китикет\"", category: Category.PET_SUPPLIES, volumeMl: null, weightGrams: 15000, purchasePrice: 3600, caseSize: 1, markup: 100, imageUrl: "/kitekat-15kg.jpg", description: "Сухой корм для взрослых кошек. Гарантированный анализ: белок 30%, жир 10%, клетчатка 3%, влага 10%." },
  { name: "Корм для кошек \"Мурчик\" с индейкой", category: Category.PET_SUPPLIES, volumeMl: null, weightGrams: 75, purchasePrice: 17.5, caseSize: 35, markup: 10, imageUrl: "/murchik-indeyka.jpg", description: "Влажный корм для кошек с индейкой в соусе. Гарантированный анализ: белок 8%, жир 5%, клетчатка 0,5%, влага 82%." },

  // Фрукты и овощи
  { name: "Черешня", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 350, caseSize: 1, markup: 49, imageUrl: "/chereshnya.jpg", description: "Свежая черешня. На 100 г: 52 ккал, Б 1,1 г, Ж 0,3 г, У 11,5 г." },
  { name: "Нектарины азербайджанские", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 140, caseSize: 1, markup: 39, imageUrl: "/nektariny-azerbaydzhan.jpg", description: "Свежие нектарины. На 100 г: 44 ккал, Б 1,1 г, Ж 0,3 г, У 10 г." },
  { name: "Томаты розовые", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 70, caseSize: 1, markup: 50, imageUrl: "/tomaty-rozoviye.jpg", description: "Свежие розовые томаты. На 100 г: 20 ккал, Б 0,9 г, Ж 0,2 г, У 3,9 г." },
  { name: "Огурцы грунтовые", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 90, caseSize: 1, markup: 20, imageUrl: "/ogurtsy-gruntoviye.jpg", description: "Свежие грунтовые огурцы. На 100 г: 15 ккал, Б 0,8 г, Ж 0,1 г, У 2,8 г." },
  { name: "Картофель", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 45, caseSize: 1, markup: 20, imageUrl: "/kartofel.jpg", description: "Свежий картофель. На 100 г: 77 ккал, Б 2 г, Ж 0,1 г, У 16,3 г." },
  { name: "Лук", category: Category.PRODUCE, volumeMl: null, weightGrams: 1000, purchasePrice: 45, caseSize: 1, markup: 15, imageUrl: "/luk.jpg", description: "Свежий репчатый лук. На 100 г: 41 ккал, Б 1,4 г, Ж 0,1 г, У 8,2 г." },
];
